# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_squashed_0011_examregistration_is_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdegree',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationdegree',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationdegree',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
