# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20170615_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdegree',
            name='seqn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
