# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20170621_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdegree',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
