# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20170921_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examapplication',
            name='application_status',
            field=models.CharField(choices=[('A', 'Approved'), ('EN', 'Enrolled'), ('D', 'Denied'), ('E', 'Expired or Deleted'), ('EB_D', 'Early Bird Denied'), ('I', 'Incomplete'), ('N', 'Not yet submitted'), ('P', 'Pending and under review'), ('R', 'Under review'), ('V_C', 'Verification Complete'), ('V_I', 'Verification Incomplete'), ('V_R', 'Verification Review')], max_length=10),
        ),
    ]
