# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20181002_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examapplication',
            name='application_status',
            field=models.CharField(choices=[('A', 'Approved'), ('A_C', 'Candidate Approved'), ('EN', 'Enrolled'), ('D', 'Denied'), ('D_C', 'Candidate Denied'), ('E', 'Expired or Deleted'), ('EB_D', 'Early Bird Denied'), ('EB_D_C', 'Candidate Early Bird Denied'), ('EB_P', 'Early Bird Pending and under review'), ('I', 'Incomplete'), ('N', 'Not yet submitted'), ('P', 'Pending and under review'), ('R', 'Under review'), ('V_C', 'Verification Complete'), ('V_I', 'Verification Incomplete'), ('V_R', 'Verification Review')], max_length=10),
        ),
    ]
