# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-16 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20190627_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examregistration',
            name='registration_type',
            field=models.CharField(choices=[('MCIP_A', 'MCIP_A: Canadian Institute of Planners (MCIP)'), ('NJ_NOAICP', 'NJ_NOAICP: NJ: registering for exam, not applying for AICP'), ('NJ_REG_A', 'NJ_REG_A: registering and applied for AICP'), ('REG_A', 'REG_A: Regular Applicant - Pre Approved'), ('REG_T_0', 'REG_T_0: Transfer from previous-no fee'), ('REG_T_100', 'REG_T_100: Transfer from previous-150$ fee'), ('SCHOLAR_A', 'SCHOLAR_A: Scholarship Recipient'), ('PDO', 'PDO: Professional Development Officer registration'), ('CAND_ENR_A', 'AICP Candidate - $100'), ('CAND_T_0', 'AICP Candidate Free Transfer - $0'), ('CAND_T_100', 'AICP Candidate Transfer - $100')], max_length=20),
        ),
    ]
