# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-24 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20191217_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdegree',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_applicationdegree_published_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationdegree',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_degree', to='myapa.School'),
        ),
        migrations.AlterField(
            model_name='applicationdegree',
            name='verification_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.VerificationDocument'),
        ),
        migrations.AlterField(
            model_name='applicationjobhistory',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_applicationjobhistory_published_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationjobhistory',
            name='verification_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.VerificationDocument'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_exam_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_exam_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examapplication',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_applications', to='myapa.IndividualContact'),
        ),
        migrations.AlterField(
            model_name='examapplication',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.ExamApplication'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_registrations', to='myapa.IndividualContact'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Purchase'),
        ),
    ]
