# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-09-01 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20200324_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICPCredentialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imis_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('open_water_user_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('candidate_application_submission_date', models.DateTimeField(blank=True, null=True)),
                ('candidate_application_status', models.CharField(blank=True, max_length=200, null=True)),
                ('candidate_essays_submission_date', models.DateTimeField(blank=True, null=True)),
                ('candidate_essays_status', models.CharField(blank=True, max_length=200, null=True)),
                ('traditional_application_submission_date', models.DateTimeField(blank=True, null=True)),
                ('traditional_application_status', models.CharField(blank=True, max_length=200, null=True)),
                ('traditional_essays_submission_date', models.DateTimeField(blank=True, null=True)),
                ('traditional_essays_status', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_registration_submission_date', models.DateTimeField(blank=True, null=True)),
                ('exam_registration_eligibility_id', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_registration_exam_window_open', models.DateTimeField(blank=True, null=True)),
                ('exam_registration_exam_window_close', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AICP Credential Data',
                'verbose_name_plural': 'AICP Credential Data',
            },
        ),
    ]
