# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    # replaces = [('places', '0001_squashed_0008_auto_20160312_0447'), ('places', '0002_auto_20160601_2336'), ('places', '0003_auto_20160706_1844'), ('places', '0004_auto_20160712_1611'), ('places', '0005_auto_20161018_1735')]

    initial = True

    dependencies = [
        # ('content', '0001_squashed_0012_auto_20161018_1735'),
        ('content', '0001_squashed_0064_auto_20160328_1819'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='publish time')),
                ('publish_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], default='DRAFT', max_length=50)),
                ('publish_uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=36, null=True)),
                ('tag_parent_state', models.BooleanField(default=True)),
                ('tag_parent_region', models.BooleanField(default=True)),
                ('tag_place_data', models.BooleanField(default=True)),
                ('sort_number', models.IntegerField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='content.Content')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places_contentplace_published_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'permissions': (('can_publish', 'Can publish'),),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='An identifier for the ending of the url - will be auto-generated based on the title for web pages.', null=True)),
                ('created_time', models.DateTimeField(editable=False)),
                ('updated_time', models.DateTimeField(editable=False)),
                ('place_type', models.CharField(choices=[('CENSUS_CITY', 'US City (or other incorporated place or census designated place)'), ('COUNTY', 'US County'), ('COUNTY_SUBDIVISION', 'US County Subdivsion'), ('STATE', 'US State'), ('CENSUS_REGION', 'US Census Region')], default='CENSUS_CITY', max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.CharField(blank=True, max_length=15, null=True)),
                ('state_name', models.CharField(blank=True, max_length=200, null=True)),
                ('place_descriptor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('census_geo_id', models.CharField(blank=True, max_length=50, null=True)),
                ('un_region_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_place_created_by', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='content.Tag')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_place_updated_by', to=settings.AUTH_USER_MODEL)),
                ('lsad', models.CharField(choices=[('21', 'Borough'), ('25', 'City'), ('37', 'Municipality'), ('43', 'Town'), ('47', 'Village'), ('53', 'City and borough'), ('55', 'Comunidad'), ('57', 'CDP'), ('62', 'Zona urbana'), ('CN', 'Corporation (incorporated place)'), ('MG', 'Metropolitan government'), ('UC', 'Urban county'), ('UG', 'Unified government'), ('00', '(other LSAD)')], default='00', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('year', models.IntegerField()),
                ('source_name', models.CharField(blank=True, max_length=200, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('housing_units', models.IntegerField(blank=True, null=True)),
                ('density', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('land_sq_miles', models.FloatField(blank=True, null=True)),
                ('water_sq_miles', models.FloatField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
        ),
        migrations.AddField(
            model_name='contentplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentplace', to='places.Place'),
        ),
        # migrations.AlterModelOptions(
        #     name='contentplace',
        #     options={'permissions': (('can_publish', 'Can publish'),)},
        # ),
        # migrations.RenameField(
        #     model_name='place',
        #     old_name='census_gio_id',
        #     new_name='census_geo_id',
        # ),
        # migrations.AddField(
        #     model_name='place',
        #     name='lsad',
        #     field=models.CharField(choices=[('21', 'Borough'), ('25', 'City'), ('37', 'Municipality'), ('43', 'Town'), ('47', 'Village'), ('53', 'City and borough'), ('55', 'Comunidad'), ('57', 'CDP'), ('62', 'Zona urbana'), ('CN', 'Corporation (incorporated place)'), ('MG', 'Metropolitan government'), ('UC', 'Urban county'), ('UG', 'Unified government'), ('00', '(other LSAD)')], default='00', max_length=5),
        # ),
        # migrations.AlterField(
        #     model_name='place',
        #     name='place_type',
        #     field=models.CharField(choices=[('CENSUS_CITY', 'US City (or other incorporated place or census designated place)'), ('COUNTY', 'US County'), ('STATE', 'US State'), ('CENSUS_REGION', 'US Census Region')], default='CENSUS_CITY', max_length=50),
        # ),
        migrations.AlterField(
            model_name='contentplace',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentplace', to='content.Content'),
        ),
        # migrations.AlterField(
        #     model_name='place',
        #     name='place_type',
        #     field=models.CharField(choices=[('CENSUS_CITY', 'US City (or other incorporated place or census designated place)'), ('COUNTY', 'US County'), ('COUNTY_SUBDIVISION', 'US County Subdivsion'), ('STATE', 'US State'), ('CENSUS_REGION', 'US Census Region')], default='CENSUS_CITY', max_length=50),
        # ),
        # migrations.AlterField(
        #     model_name='place',
        #     name='status',
        #     field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status'),
        # ),
    ]
