# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    # replaces = [('research_inquiries', '0001_initial'), ('research_inquiries', '0002_auto_20160505_2219'), ('research_inquiries', '0003_auto_20160601_2336')]

    initial = True

    dependencies = [
        ('submissions', '0001_squashed_0010_auto_20161018_1735'),
        # ('content', '0001_squashed_0012_auto_20161018_1735'),
        ('content', '0001_squashed_0064_auto_20160328_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('response_text', models.TextField(blank=True, null=True, verbose_name='Inquiry response')),
                ('review_status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDERWAY', 'Underway'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=50)),
                ('hours', models.IntegerField(help_text="Hours to deduct form org's total", blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Inquiries',
            },
            bases=('content.content', submissions.models.SubmissionModelMixin),
        ),
        migrations.CreateModel(
            name='InquiryReview',
            fields=[
            ],
            options={
                'verbose_name': 'Inquiry Assignment',
                'proxy': True,
            },
            bases=('submissions.review',),
        ),
        migrations.CreateModel(
            name='InquiryReviewRole',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('submissions.reviewrole',),
        ),
        # migrations.AlterModelOptions(
        #     name='inquiry',
        #     options={'verbose_name_plural': 'Inquiries'},
        # ),
    ]
