# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_inquiries', '0001_squashed_0003_auto_20160601_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='review_status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('ESTIMATED', 'Estimated'), ('UNDERWAY', 'Underway'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=50),
        ),
    ]
