# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squashed_0020_event_length_in_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_template',
            field=models.CharField(blank=True, choices=[('registrations/tickets/layouts/CONFERENCE-BADGE.html', 'NPC Conference Badge'), ('registrations/tickets/layouts/EVENT-MULTI.html', 'Chapter Conference Badge')], max_length=100, null=True, verbose_name='badge/ticket template'),
        ),
    ]
