# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170602_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Info event',
                'proxy': True,
            },
            bases=('events.event',),
        ),
    ]
