# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170724_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
