# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_external_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_template',
            field=models.CharField(blank=True, choices=[('registrations/tickets/layouts/CONFERENCE-BADGE.html', 'NPC Conference Badge'), ('registrations/tickets/layouts/CONFERENCE-ACTIVITY.html', 'NPC Activity Ticket'), ('registrations/tickets/layouts/CONFERENCE-PAVILION.html', 'NPC18 Pavilion Card'), ('registrations/tickets/layouts/CONFERENCE-NPC19.html', 'NPC18 Check out NPC19!'), ('registrations/tickets/layouts/CONFERENCE-FOUNDATION18.html', 'NPC18 Foundation Card'), ('registrations/tickets/layouts/EVENT-MULTI.html', 'Chapter Conference Badge'), ('registrations/tickets/layouts/ACTIVITY.html', 'Chapter Conference Activity')], max_length=100, null=True, verbose_name='badge/ticket template'),
        ),
    ]
