# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_mail_badge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NationalConferenceActivity',
        ),
        migrations.DeleteModel(
            name='NationalConferenceParticipant',
        ),
    ]
