# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('EVENT_MULTI', 'Multipart Event'), ('EVENT_SINGLE', 'Single Event'), ('ACTIVITY', 'Activity'), ('COURSE', 'On Demand'), ('EVENT_INFO', 'Informational Event'), ('LEARN_COURSE', 'APA Learn Course')], default='EVENT_SINGLE', max_length=50),
        ),
    ]
