# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20180719_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
