# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20181012_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='outside_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
