# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-13 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_outside_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_early_cutoff_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='early pricing cutoff time'),
        ),
        migrations.AddField(
            model_name='event',
            name='price_late_cutoff_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='late pricing cutoff time'),
        ),
        migrations.AddField(
            model_name='event',
            name='price_regular_cutoff_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='regular pricing cutoff time'),
        ),
    ]
