# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20190125_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voter_voice_checksum',
            field=models.CharField(blank=True, help_text='The checksum that is returned by a VoterVoice-validated address', max_length=100, null=True),
        ),
    ]
