# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170525_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact_us_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
