# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-29 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20181012_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('INTERN', 'Internship'), ('ENTRY_LEVEL', 'Entry-level job - 4 weeks online'), ('PROFESSIONAL_2_WEEKS', 'Professional job - 2 weeks online'), ('PROFESSIONAL_4_WEEKS', 'Professional job - 4 weeks online'), ('PROFESSIONAL_4_WEEKS_100', 'Professional (various levels of experience) - 4 weeks online'), ('PROFESSIONAL_4_WEEKS_75', 'Professional (various levels of experience) - 4 weeks online'), ('PROFESSIONAL_4_WEEKS_50', 'Professional (various levels of experience) - 4 weeks online'), ('PROFESSIONAL_4_WEEKS_0', 'Professional (various levels of experience) - 4 weeks online'), ('PROFESSIONAL_2_WEEKS_75', 'Professional (various levels of experience) - 2 weeks online'), ('PROFESSIONAL_2_WEEKS_50', 'Professional (various levels of experience) - 2 weeks online'), ('PROFESSIONAL_2_WEEKS_0', 'Professional (various levels of experience) - 2 weeks online'), ('ENTRY_LEVEL_50', 'Entry Level only (zero to one year of experience; not AICP) - 4 weeks online'), ('ENTRY_LEVEL_0', 'Entry Level only (zero to one year of experience; not AICP) - 4 weeks online'), ('INTERN_0', 'Internship only (temporary position; no experience required) - 4 weeks online'), ('FEATURED_2_WEEKS', 'Featured job - 2 weeks online')], default='PROFESSIONAL_4_WEEKS', max_length=50),
        ),
    ]
