# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-27 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20181029_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailJob',
            fields=[
            ],
            options={
                'verbose_name': 'Wagtail Job',
                'proxy': True,
                'indexes': [],
            },
            bases=('jobs.job',),
        ),
    ]
