# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-08-04 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20210803_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_url',
        ),
    ]
