# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_squashed_0041_auto_20160312_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_tribute', models.BooleanField(default=False)),
                ('tribute_honoree', models.CharField(blank=True, max_length=200)),
                ('tribute_email', models.EmailField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('A', 'Active'), ('H', 'Hidden'), ('N', 'Not Submitted')], default='A', max_length=5)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Purchase')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='last_updated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
