# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170111_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('H', 'Hidden'), ('N', 'Not Submitted')], default='N', max_length=5),
        ),
    ]
