# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170427_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='submitted_product_price_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='amount to be charged'),
        ),
    ]
