# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170831_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Yet Submitted'), ('SUBMITTED', 'Submitted'), ('PROCESSED', 'Processed (archived)'), ('CANCELLED', 'Cancelled'), ('SUBMITTED_FAILED', 'Submitted, not in iMIS')], default='NOT_SUBMITTED', max_length=20),
        ),
    ]
