# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180411_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLearnCourse',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('store.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Default Product Type'), ('CANCELLATION', 'Cancellation/Refund'), ('CANCELLATION_FEE', 'Cancellation Fee($50)'), ('EVENT_REGISTRATION', 'Event Registration'), ('PUBLICATION_SUBSCRIPTION', 'Publication/Subscription'), ('ACTIVITY_TICKET', 'Event Activity Ticket'), ('CM_REGISTRATION', 'CM Annual Registrations'), ('CM_PER_CREDIT', 'CM Per-Credit Payments'), ('DUES', 'Membership Dues'), ('DIGITAL_PUBLICATION', 'Digital Publications'), ('CHAPTER', 'Chapter'), ('DIVISION', 'Division'), ('BOOK', 'Book'), ('DONATION', 'Donation'), ('EBOOK', 'E-book'), ('STREAMING', 'Streaming'), ('AICP_CANDIDATE_ENROLLMENT', 'AICP Candidate Enrollment'), ('EXAM_APPLICATION', 'Exam Application'), ('EXAM_REGISTRATION', 'Exam Registration'), ('SHIPPING', 'Shipping'), ('TAX', 'Tax'), ('AWARD', 'Awards'), ('ADJUSTMENT', 'Adjustment'), ('JOB_AD', 'Job Ad'), ('RESEARCH_INQUIRY', 'Research Inquiry'), ('LEARN_COURSE', 'APA Learn Course')], help_text='leave blank to auto-populate', max_length=50),
        ),
    ]
