# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-13 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20180710_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='for_someone_else',
            field=models.BooleanField(default=False, help_text='Will this purchase be redeemed by someone else? \n        (used to indicate that a "group license code" should be generated for an LMS purchase \n        as opposed to immediate access for purchaser).'),
        ),
    ]
