# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-02 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_purchase_for_someone_else'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('store.product',),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='product',
        ),
        migrations.DeleteModel(
            name='BookContent',
        ),
        migrations.DeleteModel(
            name='ProductBook',
        ),
        migrations.DeleteModel(
            name='ProductChapter',
        ),
        migrations.DeleteModel(
            name='ProductDigitalPublication',
        ),
        migrations.DeleteModel(
            name='ProductDivision',
        ),
        migrations.DeleteModel(
            name='ProductEBook',
        ),
        migrations.DeleteModel(
            name='ProductPublished',
        ),
        migrations.DeleteModel(
            name='ProductShipping',
        ),
        migrations.DeleteModel(
            name='ProductSubscription',
        ),
        migrations.DeleteModel(
            name='ProductTax',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='for_someone_else',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
