# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-02 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20170929_1540'),
        ('directories', '0003_auto_20170207_1630'),
        ('store', '0012_auto_20181102_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('store.product',),
        ),
    ]
