# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-13 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20181012_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='event_pricing_cutoff_type',
            field=models.CharField(blank=True, choices=[('EARLY', 'Early'), ('REGULAR', 'Regular'), ('LATE', 'Late')], help_text='For iMIS events to link registrants with early, regular, or late registration pricing.', max_length=20, null=True),
        ),
    ]
