# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-16 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productprice_event_pricing_cutoff_type'),
        ('store', '0013_auto_20181102_1511'),
    ]

    operations = [
    ]
