# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-01 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20190503_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
