# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20190801_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='voter_voice_checksum',
            field=models.CharField(blank=True, help_text='The checksum that is returned by a VoterVoice-validated address', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='voter_voice_checksum',
            field=models.CharField(blank=True, help_text='The checksum that is returned by a VoterVoice-validated address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='for_someone_else',
            field=models.BooleanField(default=False, help_text='Will this purchase be redeemed by someone else?\n        (used to indicate that a "group license code" should be generated for an LMS purchase\n        as opposed to immediate access for purchaser).'),
        ),
    ]
