# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-03-29 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20200324_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_check_number',
            field=models.CharField(blank=True, help_text='For check or credit card payments: enter check number or credit card ending digits\n                for payments processed manually.\n                DO NOT enter full credit card numbers in this field.', max_length=50, null=True, verbose_name='Check number / credit card ending digits'),
        ),
    ]
