# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-06 15:31
from __future__ import unicode_literals

import component_sites.blocks
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    # replaces = [('component_sites', '0001_initial'), ('component_sites', '0002_auto_20170315_1532'), ('component_sites', '0003_auto_20170321_1041'), ('component_sites', '0004_chapterhomepage_additional_content'), ('component_sites', '0005_auto_20170323_1623'), ('component_sites', '0006_auto_20170323_1736'), ('component_sites', '0007_landingpage_standardpage'), ('component_sites', '0008_auto_20170613_1651'), ('component_sites', '0009_newspage'), ('component_sites', '0010_auto_20170622_1610'), ('component_sites', '0011_auto_20170627_1538'), ('component_sites', '0012_standardpage_tag_tree_streamfield'), ('component_sites', '0013_auto_20170627_1659'), ('component_sites', '0014_auto_20170627_1709'), ('component_sites', '0015_auto_20170629_1736'), ('component_sites', '0016_auto_20170630_1038'), ('component_sites', '0017_auto_20170630_1203'), ('component_sites', '0018_auto_20170630_1238'), ('component_sites', '0019_auto_20170630_1639'), ('component_sites', '0020_remove_taxonewspage_tags'), ('component_sites', '0021_auto_20170705_1506'), ('component_sites', '0022_auto_20170705_1616'), ('component_sites', '0023_auto_20170705_1652')]

    initial = True

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('submissions', '0001_squashed_0010_auto_20161018_1735'),
        ('content', '0008_auto_20170502_1135'),
        ('myapa', '0009_auto_20170619_1712'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('places', '0001_squashed_0005_auto_20161018_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('featured_content', wagtail.wagtailcore.fields.StreamField((('feature1', wagtail.wagtailcore.blocks.StructBlock((('overline', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('button', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock()))))))), ('feature2', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())))), ('feature3', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()))))))),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DivisionHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('additional_content', wagtail.wagtailcore.fields.StreamField((('video', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('video', wagtail.wagtailcore.blocks.URLBlock(help_text='url for youtube video')), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('photo_gallery', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('photos', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('tiled_images', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('images', wagtail.wagtailcore.blocks.ListBlock(component_sites.blocks.LinkedImageBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('text', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('feature_list', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('listed_links', wagtail.wagtailcore.blocks.ListBlock(component_sites.blocks.LinkBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('events', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)),))), ('news', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)),))), ('npc_activities', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)),)))), default=[])),
                ('featured_content', wagtail.wagtailcore.fields.StreamField((('feature', wagtail.wagtailcore.blocks.StructBlock((('Featured_Text', wagtail.wagtailcore.blocks.CharBlock(help_text='Help text for Featured Text/Overline', required=True)), ('Headline', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Intro_Text', wagtail.wagtailcore.blocks.RichTextBlock()), ('Inset_Image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('secondary_features', wagtail.wagtailcore.blocks.StructBlock((('feature1', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('feature2', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))))))), default=[])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='chapterhomepage',
            name='events_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='chapterhomepage',
            name='include_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chapterhomepage',
            name='include_jobs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapterhomepage',
            name='include_news',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chapterhomepage',
            name='jobs_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='chapterhomepage',
            name='news_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='chapterhomepage',
            name='featured_content',
            field=wagtail.wagtailcore.fields.StreamField((('feature', wagtail.wagtailcore.blocks.StructBlock((('overline', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('button', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock()))))))), ('secondaryFeatures', wagtail.wagtailcore.blocks.StructBlock((('feature1', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock()))))))), ('feature2', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock())))))))))))),
        ),
        migrations.AddField(
            model_name='chapterhomepage',
            name='additional_content',
            field=wagtail.wagtailcore.fields.StreamField((('video', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('video', wagtail.wagtailcore.blocks.URLBlock(help_text='url for youtube video')), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('photo_gallery', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('photos', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('imag_with_links', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('url', wagtail.wagtailcore.blocks.URLBlock())))), ('listed_links', wagtail.wagtailcore.blocks.ListBlock(component_sites.blocks.LinkBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('tiled_images', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('images', wagtail.wagtailcore.blocks.ListBlock(component_sites.blocks.LinkedImageBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')]))))))))), default=[]),
        ),
        migrations.AlterField(
            model_name='chapterhomepage',
            name='featured_content',
            field=wagtail.wagtailcore.fields.StreamField((('feature', wagtail.wagtailcore.blocks.StructBlock((('overline', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('secondaryFeatures', wagtail.wagtailcore.blocks.StructBlock((('feature1', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('feature2', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')]))))))))))))),
        ),
        migrations.AlterField(
            model_name='chapterhomepage',
            name='featured_content',
            field=wagtail.wagtailcore.fields.StreamField((('feature', wagtail.wagtailcore.blocks.StructBlock((('overline', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('secondaryFeatures', wagtail.wagtailcore.blocks.StructBlock((('feature1', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('feature2', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')]))))))))))))),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('featured_content', wagtail.wagtailcore.fields.StreamField((('feature', wagtail.wagtailcore.blocks.StructBlock((('Featured_Text', wagtail.wagtailcore.blocks.CharBlock(help_text='Help text for Featured Text/Overline', required=True)), ('Headline', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Intro_Text', wagtail.wagtailcore.blocks.RichTextBlock()), ('Inset_Image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))),), default=[])),
                ('body', wagtail.wagtailcore.fields.RichTextField()),
                ('additional_content', wagtail.wagtailcore.fields.StreamField((('features_section', wagtail.wagtailcore.blocks.StreamBlock((('video', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('video', wagtail.wagtailcore.blocks.URLBlock(help_text='url for youtube video')), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('photo_gallery', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('photos', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('tiled_images', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('images', wagtail.wagtailcore.blocks.ListBlock(component_sites.blocks.LinkedImageBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('text', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('feature_list', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('listed_links', wagtail.wagtailcore.blocks.ListBlock(component_sites.blocks.LinkBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('events', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)),))), ('news', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)),))), ('npc_activities', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)),)))))), ('columns_of_links_section', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('listed_links', wagtail.wagtailcore.blocks.ListBlock(component_sites.blocks.LinkBlock)), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))), template='component-sites/component-theme/blocks/feature-link-list-section.html'))), default=[])),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('header', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)),))), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')]))))), ('call_out', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subheading', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('body', wagtail.wagtailcore.blocks.RichTextBlock())))), ('bio', wagtail.wagtailcore.blocks.StructBlock((('detail', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))))), ('pull_quote', wagtail.wagtailcore.blocks.StructBlock((('body', wagtail.wagtailcore.blocks.RichTextBlock()),))), ('image_with_caption', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('image_with_text', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('image_style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('image-block-float-right', 'Float Right'), ('image-block-float-left', 'Float Left')])), ('body', wagtail.wagtailcore.blocks.RichTextBlock())))), ('table', component_sites.blocks.ResponsiveTableBlock())), default=[])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='chapterhomepage',
            name='featured_content',
            field=wagtail.wagtailcore.fields.StreamField((('feature', wagtail.wagtailcore.blocks.StructBlock((('Featured_Text', wagtail.wagtailcore.blocks.CharBlock(help_text='Help text for Featured Text/Overline', required=True)), ('Headline', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Intro_Text', wagtail.wagtailcore.blocks.RichTextBlock()), ('Inset_Image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('secondary_features', wagtail.wagtailcore.blocks.StructBlock((('feature1', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')])))))))), ('feature2', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')]))))))))))))),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('post_time', models.DateTimeField(blank=True, null=True, verbose_name='post time')),
                ('body', wagtail.wagtailcore.fields.StreamField((('header', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)),))), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')]))))), ('call_out', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subheading', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('body', wagtail.wagtailcore.blocks.RichTextBlock())))), ('bio', wagtail.wagtailcore.blocks.StructBlock((('detail', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))))), ('pull_quote', wagtail.wagtailcore.blocks.StructBlock((('body', wagtail.wagtailcore.blocks.RichTextBlock()),))), ('image_with_caption', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('image_with_text', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('image_style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('image-block-float-right', 'Float Right'), ('image-block-float-left', 'Float Left')])), ('body', wagtail.wagtailcore.blocks.RichTextBlock())))), ('table', component_sites.blocks.ResponsiveTableBlock())), default=[])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CMSDataHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CommunityTypeTag',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagtailcommunitytype', to='content.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JurisdictionTag',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagtailjurisdiction', to='content.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPageRelatedCommunityTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_communitytypes', to='component_sites.NewsPage')),
                ('related_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.CommunityTypeTag')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPageRelatedJurisdictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_jurisdictions', to='component_sites.NewsPage')),
                ('related_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.JurisdictionTag')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPageRelatedTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_topics', to='component_sites.NewsPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagtailtopic', to='content.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='newspagerelatedtopics',
            name='related_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.TopicTag'),
        ),
    ]
