# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20170816_1813'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('component_sites', '0005_chapterhomepagerelatedcommunitytypes_chapterhomepagerelatedjurisdictions_chapterhomepagerelatedtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterhomepagerelatedcommunitytypes',
            name='page',
        ),
        migrations.RemoveField(
            model_name='chapterhomepagerelatedcommunitytypes',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='chapterhomepagerelatedjurisdictions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='chapterhomepagerelatedjurisdictions',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='chapterhomepagerelatedtopics',
            name='page',
        ),
        migrations.RemoveField(
            model_name='chapterhomepagerelatedtopics',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='cmsdatahomepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='divisionhomepagerelatedcommunitytypes',
            name='page',
        ),
        migrations.RemoveField(
            model_name='divisionhomepagerelatedcommunitytypes',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='divisionhomepagerelatedjurisdictions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='divisionhomepagerelatedjurisdictions',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='divisionhomepagerelatedtopics',
            name='page',
        ),
        migrations.RemoveField(
            model_name='divisionhomepagerelatedtopics',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedcommunitytypes',
            name='page',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedcommunitytypes',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedjurisdictions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedjurisdictions',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedtopics',
            name='page',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedtopics',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='newspagerelatedcommunitytypes',
            name='page',
        ),
        migrations.RemoveField(
            model_name='newspagerelatedcommunitytypes',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='newspagerelatedjurisdictions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='newspagerelatedjurisdictions',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='newspagerelatedtopics',
            name='page',
        ),
        migrations.RemoveField(
            model_name='newspagerelatedtopics',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='standardpagerelatedcommunitytypes',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpagerelatedcommunitytypes',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='standardpagerelatedjurisdictions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpagerelatedjurisdictions',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='standardpagerelatedtopics',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpagerelatedtopics',
            name='related_tag',
        ),
        migrations.RemoveField(
            model_name='communitytypetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='jurisdictiontag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='topictag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ChapterHomePageRelatedCommunityTypes',
        ),
        migrations.DeleteModel(
            name='ChapterHomePageRelatedJurisdictions',
        ),
        migrations.DeleteModel(
            name='ChapterHomePageRelatedTopics',
        ),
        migrations.DeleteModel(
            name='CMSDataHomePage',
        ),
        migrations.DeleteModel(
            name='DivisionHomePageRelatedCommunityTypes',
        ),
        migrations.DeleteModel(
            name='DivisionHomePageRelatedJurisdictions',
        ),
        migrations.DeleteModel(
            name='DivisionHomePageRelatedTopics',
        ),
        migrations.DeleteModel(
            name='LandingPageRelatedCommunityTypes',
        ),
        migrations.DeleteModel(
            name='LandingPageRelatedJurisdictions',
        ),
        migrations.DeleteModel(
            name='LandingPageRelatedTopics',
        ),
        migrations.DeleteModel(
            name='NewsPageRelatedCommunityTypes',
        ),
        migrations.DeleteModel(
            name='NewsPageRelatedJurisdictions',
        ),
        migrations.DeleteModel(
            name='NewsPageRelatedTopics',
        ),
        migrations.DeleteModel(
            name='StandardPageRelatedCommunityTypes',
        ),
        migrations.DeleteModel(
            name='StandardPageRelatedJurisdictions',
        ),
        migrations.DeleteModel(
            name='StandardPageRelatedTopics',
        ),
        migrations.AddField(
            model_name='communitytypetag',
            name='related_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagtail_communitytype_tag', to='content.Tag'),
        ),
        migrations.AddField(
            model_name='jurisdictiontag',
            name='related_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagtail_jurisdiction_tag', to='content.Tag'),
        ),
        migrations.AddField(
            model_name='topictag',
            name='related_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagtail_topic_tag', to='content.Tag'),
        )
    ]
