# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-07 16:34
from __future__ import unicode_literals

import component_sites.blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('component_sites', '0007_tagtyperelationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('header', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)),))), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')]))))), ('call_out', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subheading', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('body', wagtail.wagtailcore.blocks.RichTextBlock())))), ('bio', wagtail.wagtailcore.blocks.StructBlock((('detail', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('description', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))))), ('pull_quote', wagtail.wagtailcore.blocks.StructBlock((('body', wagtail.wagtailcore.blocks.RichTextBlock()),))), ('image_with_caption', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('image_with_text', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('image_style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('image-block-float-right', 'Float Right'), ('image-block-float-left', 'Float Left')])), ('body', wagtail.wagtailcore.blocks.RichTextBlock())))), ('table', component_sites.blocks.ResponsiveTableBlock())), default=[]),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('header', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock(required=True)),))), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.StructBlock((('Link_Text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('Link_URL', wagtail.wagtailcore.blocks.URLBlock()), ('Link_Style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('REGULAR', 'Regular Link'), ('BUTTON', 'Button'), ('FANCY', 'Fancy Link')]))))), ('call_out', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subheading', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('body', wagtail.wagtailcore.blocks.RichTextBlock())))), ('bio', wagtail.wagtailcore.blocks.StructBlock((('detail', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('description', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))))), ('pull_quote', wagtail.wagtailcore.blocks.StructBlock((('body', wagtail.wagtailcore.blocks.RichTextBlock()),))), ('image_with_caption', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('image_with_text', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('image_style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('image-block-float-right', 'Float Right'), ('image-block-float-left', 'Float Left')])), ('body', wagtail.wagtailcore.blocks.RichTextBlock())))), ('table', component_sites.blocks.ResponsiveTableBlock())), default=[]),
        ),
    ]
