# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component_sites', '0009_auto_20190603_1406_squashed_0013_auto_20190604_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterhomepage',
            name='events_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='chapterhomepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='chapterhomepage',
            name='jobs_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='chapterhomepage',
            name='news_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='divisionhomepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
    ]
