# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-24 20:55
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_sites', '0011_auto_20190724_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearancesettings',
            name='color',
            field=colorful.fields.RGBColorField(default='#165788'),
        ),
    ]
