# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component_sites', '0012_auto_20190724_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
    ]
