# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-31 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component_sites', '0013_auto_20190730_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='default_og_image',
            field=models.ForeignKey(blank=True, help_text='OG image for pages with no assigned og image. Should be logo with recommended size 1200x630px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='chapterhomepage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for shared link, at least two sentences long.', null=True),
        ),
        migrations.AlterField(
            model_name='chapterhomepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image for shared link. Facebook recommends 1200 x 630 pixels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='divisionhomepage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for shared link, at least two sentences long.', null=True),
        ),
        migrations.AlterField(
            model_name='divisionhomepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Description for shared link, at least two sentences long.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for shared link, at least two sentences long.', null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Description for shared link, at least two sentences long.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for shared link, at least two sentences long.', null=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Description for shared link, at least two sentences long.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for shared link, at least two sentences long.', null=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Description for shared link, at least two sentences long.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='component_sites.ComponentImage'),
        ),
    ]
