# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-21 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_sites', '0014_auto_20190731_1110'),
        ('component_sites', '0013_auto_20190805_1357'),
    ]

    operations = [
    ]
