CURRENT_EXAM = ("2018MAY", "May 2018")

EXAM_APP_EMAIL_TEMPLATES = {
    "A": "EXAM_APPLICATION_AICP_APPROVED",
    "I": "EXAM_APPLICATION_AICP_INCOMPLETE",
    "P": "EXAM_APPLICATION_AICP_PENDING",
    "R": "EXAM_APPLICATION_AICP_REVIEW_CONFIRMATION",
    "V_C": "EXAM_APPLICATION_AICP_REVIEW_CONFIRMATION",
    "V_R": "EXAM_APPLICATION_AICP_REVIEW_CONFIRMATION",
    "V_I": "EXAM_APPLICATION_AICP_INVALID_DOCUMENTS",
}

CAND_ENROLL_EMAIL_TEMPLATES = {
    "A": "APPROVED_CANDIDATE",
    "EN": "ENROLLED_CANDIDATE",
    "I": "EXAM_APPLICATION_AICP_CANDIDATE_INCOMPLETE",
    "P": "PENDING_CANDIDATE",
}

CAND_CERT_EMAIL_TEMPLATES = {
    "A_C": "EXAM_APPLICATION_AICP_CANDIDATE_APPROVED",
    "D_C": "EXAM_APPLICATION_AICP_CANDIDATE_DENIED",
    "I": "EXAM_APPLICATION_AICP_INCOMPLETE",
    "P": "EXAM_APPLICATION_AICP_PENDING",
    "R": "EXAM_APPLICATION_AICP_REVIEW_CONFIRMATION",
    "V_C": "EXAM_APPLICATION_AICP_REVIEW_CONFIRMATION",
    "V_R": "EXAM_APPLICATION_AICP_REVIEW_CONFIRMATION",
    "V_I": "EXAM_APPLICATION_AICP_INVALID_DOCUMENTS",
}

CAND_ENROLL_APP_TYPES = ["CAND_ENR"]
CAND_CERT_APP_TYPES = ["CAND_CERT", "CAND_RESUB"]
APP_STATUS_IGNORE_LIST = ["D", "E", "EB_D", "EB_D_C", "N"]

OPEN_WATER_API_URL = "https://api.secure-platform.com/v2/Invoices/"
