# TO DO... insert config code here for each chapter/division

COMPONENT_SITES = {
    "planning.org": {
        "site": "planning.org",
        "verbose_name": "",
        "type": "",
        "logo_block": "",
        "logo_signature": "content/image/APA_horizontal_647.jpg",
        "username": "119523",
        "addl_providers": "",
        "color": "",
        "jobs_product_code": "JOB_AD_CONTENT",
        "job_post_instruction_code": "JOBS_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB",
        "directory_code": "DIRECTORY_MEMBER",
        "favicon": "content/image/favicon.ico",
        "facebook": "",
        "youtube": "",
        "twitter": "",
        "instagram": "",
        "linkedin": "",
        "dummy":True

    },
    "chapter.planning.org": {
        "site": "chapter.planning.org",
        "verbose_name": "",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/virginia/logo.svg",
        "logo_signature": "component-sites/image/virginia/signature.svg",
        "username": "136431",
        "addl_providers": "",
        "color": "137, 37, 40",
        "jobs_product_code": "JOB_AD_CHAPT_VA",
        "job_post_instruction_code": "VA_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_VA",
        "directory_code": "DIRECTORY_CHAPT_VA",
        "favicon": "component-sites/image/virginia/favicon.ico",
        "facebook": "",
        "youtube": "",
        "twitter": "",
        "instagram": "",
        "linkedin": "",
        "dummy":True

    },
    "alaska.planning.org": {
        "site": "alaska.planning.org",
        "verbose_name": "Alaska",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/virginia/logo.svg",
        "logo_signature": "component-sites/image/virginia/signature.svg",
        "username": "136431",
        "addl_providers": "",
        "color": "137, 37, 40",
        "jobs_product_code": "JOB_AD_CHAPT_VA",
        "job_post_instruction_code": "VA_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_VA",
        "directory_code": "DIRECTORY_CHAPT_VA",
        "favicon": "component-sites/image/virginia/favicon.ico",
        "facebook": "",
        "youtube": "",
        "twitter": "",
        "instagram": "",
        "linkedin": "",
        "dummy":True

    },
    "division.planning.org": {
        "site": "division.planning.org",
        "verbose_name": "",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/urban-design/logo.png",
        "logo_signature": "component-sites/image/urban-design/signature.png",
        "username": "184881",
        "addl_providers": "",
        "color": "132, 122, 23",
        "jobs_product_code": "JOB_AD_URBAN_DES",
        "job_post_instruction_code": "UD_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_URBAN_DES",
        "directory_code": "DIRECTORY_URBAN_DES",
        "favicon": "component-sites/image/urban-design/favicon.ico",
        "facebook": "",
        "youtube": "",
        "twitter": "",
        "instagram": "",
        "linkedin": "",
        "dummy":True
    },

    "arizona.planning.org": {
        "site": "arizona.planning.org",
        "verbose_name": "Arizona",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/arizona/AZ_logo_634.png",
        "logo_signature": "component-sites/image/arizona/AZ_horizontal_634.png",
        "username": "185753",
        "addl_providers": "",
        "color": "0, 127, 110",
        "jobs_product_code": "JOB_AD_CHAPT_AZ",
        "job_post_instruction_code": "AZ_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_AZ",
        "directory_code": "DIRECTORY_AZ",
        "favicon": "component-sites/image/arizona/favicon.ico",
        "facebook": "American-Planning-Association-Arizona-Chapter-164228463734746",
        "youtube": "channel/UCrx9QvaCQMP-CZspxlJh1iA",
        "twitter": "azplanning",
        "instagram": "americanplanningassociation",
        "linkedin": "groups/3075568/",
        "admin_group":"CHAPT_AZ-admin"
    },

    "blackcommunity.planning.org": {
        "site":"blackcommunity.planning.org",
        "verbose_name": "Black Community",
        "static": "blackcommunity",
        "type": "DIVISION",
        "logo_block": "component-sites/image/blackcommunity/BlackComm_647+266.png",
        "logo_signature":"component-sites/image/blackcommunity/BlackComm_horizontal_647+266.png",
        "username": "209255",
        "addl_providers": "",
        "tag_code": "BLACK_COMMUNITY",
        "color": "119, 61, 189",
        "jobs_product_code": "JOB_AD_BLACK",
        "job_post_instruction_code": "BLACK_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_BLACK",
        "directory_code": "DIRECTORY_BLACK",
        "favicon": "component-sites/image/blackcommunity/favicon.ico",
        "facebook": "apablackcommunitydivision",
        "youtube": "channel/UC8J5WXnXgoN4wBGvdELbrNw",
        "twitter": "pbcdiv",
        "instagram": "explore/locations/16246435/american-planning-association",
        "linkedin": "groups/4109746",
        "admin_group":"BLACK-admin"
    },


    "california.planning.org": {
        "site": "california.planning.org",
        "verbose_name": "California",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/california/CA_logo_7408.png",
        "logo_signature": "component-sites/image/california/CA_horizontal_7408.png",
        "username": "186020",
        "addl_providers": "",
        "color": "247, 190, 0",
        "jobs_product_code": "JOB_AD_CHAPT_CA",
        "job_post_instruction_code": "CA_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_CA",
        "directory_code": "DIRECTORY_CA",
        "favicon": "component-sites/image/california/favicon.ico",
        "facebook": "pages/APA-California/272665912772004",
        "youtube": "",
        "twitter": "APA_California",
        "instagram": "",
        "linkedin": "groups?gid=2063002&trk=myg_ugrp_ovr",
        "admin_group":"CHAPT_CA-admin"
    },

    "city.planning.org": {
        "site": "city.planning.org",
        "verbose_name": "City Planning",
        "static": "city",
        "type": "DIVISION",
        "logo_block": "component-sites/image/city/CityPlanning_647+376.png",
        "logo_signature": "component-sites/image/city/CityPlanning_horizontal_647+376.png",
        "username": "184880",
        "addl_providers": "",
        "tag_code": "CITY",
        "color": "148, 147, 0",
        "jobs_product_code": "JOB_AD_CITY",
        "job_post_instruction_code": "CITY_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CITY",
        "directory_code": "DIRECTORY_CITY",
        "favicon": "component-sites/image/city/favicon.ico",
        "facebook": "",
        "youtube": "",
        "twitter": "",
        "instagram": "",
        "linkedin": "",
        "admin_group":"CITY_PLAN-admin"
    },

    "ct.planning.org": {
        "site": "ct.planning.org",
        "verbose_name": "Connecticut",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/connecticut/CT_logo_7412.png",
        "logo_signature": "component-sites/image/connecticut/CT_horizontal_7412.png",
        "username": "214541",
        "addl_providers": "",
        "color": "212, 130, 50",
        "jobs_product_code": "JOB_AD_CHAPT_CT",
        "job_post_instruction_code": "CT_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_CT",
        "directory_code": "DIRECTORY_CHAPT_CT",
        "favicon": "component-sites/image/connecticut/favicon.ico",
        "facebook": "CTPLANNING",
        "youtube": "",
        "twitter": "CT_APA",
        "instagram": "",
        "linkedin": "",
        "admin_group":"CHAPT_CT-admin"
    },

    "florida.planning.org": {
        "site": "florida.planning.org",
        "verbose_name": "Florida",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/florida/FL_logo_569.png",
        "logo_signature": "component-sites/image/florida/FL_horizontal_569.png",
        "username": "159585",
        "addl_providers": "243458,243458,243456,243457,221868,222533,224001,227563,219561,225532,243462,219773,243461",
        "color": "0, 127, 110",
        "jobs_product_code": "JOB_AD_CHAPT_FL",
        "job_post_instruction_code": "FL_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_FL",
        "directory_code": "DIRECTORY_FL",
        "favicon": "component-sites/image/florida/favicon.ico",
        "facebook": "APAFlorida",
        "youtube": "channel/UCrKSFANF5u12cRM198zdMLQ",
        "twitter": "APAFlorida",
        "instagram": "",
        "linkedin": "company/apa-florida",
        "admin_group":"CHAPT_FL-admin"
    },
    "hawaii.planning.org": {
        "site": "hawaii.planning.org",
        "verbose_name": "Hawai‘i",
        "static": "hawaii",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/hawaii/HI_logo_268.png",
        "logo_signature": "component-sites/image/hawaii/HI_horizontal_268.png",
        "username": "214543",
        "addl_providers": "",
        "color": "89, 44, 130",
        "jobs_product_code": "JOB_AD_CHAPT_HI",
        "job_post_instruction_code": "HI_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_HI",
        "directory_code": "DIRECTORY_HI",
        "favicon": "component-sites/image/hawaii/favicon.ico",
        "facebook": "apa.hawaii.chapter",
        "youtube": "",
        "twitter": "",
        "linkedin": "",
        "admin_group": "CHAPT_HI-admin"
    },

    "housing.planning.org": {
        "site": "housing.planning.org",
        "verbose_name": "Housing",
        "type": "DIVISION",
        "logo_block": "component-sites/image/housing/HousingCD.png",
        "logo_signature": "component-sites/image/housing/HousingCD_horizontal_647+348.png",
        "username": "184882",
        "addl_providers": "",
        "tag_code": "HOUSING",
        "color": "148, 147, 0",
        "jobs_product_code": "JOB_AD_HOUSING",
        "job_post_instruction_code": "HOUSING_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_HOUSING",
        "directory_code": "DIRECTORY_HOUSING",
        "favicon": "component-sites/image/housing/favicon.ico",
        "facebook": "",
        "youtube": "",
        "twitter": "",
        "instagram": "",
        "linkedin": "",
        "admin_group":"HOUSING-admin"
    },

    "iowa.planning.org": {
        "site": "iowa.planning.org",
        "verbose_name": "Iowa",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/iowa/IA_logo_7408.jpg",
        "logo_signature": "component-sites/image/iowa/IA_horizontal_7408.png",
        "username": "214545",
        "addl_providers": "",
        "color": "247, 190, 0",
        "jobs_product_code": "JOB_AD_CHAPT_IA",
        "job_post_instruction_code": "IA_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_IA",
        "directory_code": "DIRECTORY_IA",
        "favicon": "component-sites/image/iowa/favicon.ico",
        "facebook": "IowaAPAChapter",
        "youtube": "",
        "twitter": "iowaapachapter",
        "instagram": "",
        "linkedin": "company/iowa-apa-chapter/",
        "admin_group":"CHAPT_IA-admin"
    },

     "kansas.planning.org": {
        "site": "kansas.planning.org",
        "verbose_name": "Kansas",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/kansas/KS_logo_117.png",
        "logo_signature": "component-sites/image/kansas/KS_horizontal_117.png",
        "username": "212738",
        "addl_providers": "",
        "color": "203, 151, 0",
        "jobs_product_code": "JOB_AD_CHAPT_KS",
        "job_post_instruction_code": "KS_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_KS",
        "directory_code": "DIRECTORY_KS",
        "favicon": "component-sites/image/kansas/favicon.ico",
        "facebook": "KansasAPA",
        "youtube": "channel/UC8J5WXnXgoN4wBGvdELbrNw",
        "twitter": "APA_KS",
        "linkedin": "groups/116818",
        "admin_group": "CHAPT_KS-admin"
    },

    "missouri.planning.org": {

        "site": "missouri.planning.org",
        "verbose_name": "Missouri",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/missouri/MO_logo_7447.png",
        "logo_signature": "component-sites/image/missouri/MO_horizontal_7447.png",
        "username": "214547",
        "addl_providers": "",
        "color": "99, 97, 154",
        "jobs_product_code": "JOB_AD_CHAPT_MO",
        "job_post_instruction_code": "MO_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_MO",
        "directory_code": "DIRECTORY_CHAPT_MO",
        "favicon": "component-sites/image/missouri/favicon.ico",
        "facebook": "APAMissouri",
        "youtube": "channel/UC8J5WXnXgoN4wBGvdELbrNw",
        "twitter": "APAMissouri",
        "instagram": "explore/locations/16246435/american-planning-association/",
        "linkedin": "company/american-planning-association/",
        "admin_group":"CHAPT_MI-admin"
    },

    "ncac.planning.org": {
        "site": "ncac.planning.org",
        "verbose_name": "National Capital Area",
        "static":"ncac",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/ncac/NCA_logo_634.png",
        "logo_signature": "component-sites/image/ncac/NCA_horizontal_634.png",
        "username": "214548",
        "addl_providers": "",
        "color": "0, 93, 131",
        "jobs_product_code": "JOB_AD_CHAPT_NCAC",
        "job_post_instruction_code": "NCAC_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_NCAC",
        "directory_code": "DIRECTORY_CHAPT_NCAC",
        "favicon": "component-sites/image/ncac/favicon.ico",
        "facebook": "NCACAPA",
        "youtube": "",
        "twitter": "NCAC_APA",
        "instagram": "",
        "linkedin": "",
        "admin_group": "CHAPT_NCAC-admin"
    },

    "nebraska.planning.org": {
        "site": "nebraska.planning.org",
        "verbose_name": "Nebraska",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/nebraska/NE_logo_7412.png",
        "logo_signature": "component-sites/image/nebraska/NE_horizontal_7412.png",
        "username": "214549",
        "addl_providers": "",
        "color": "212, 130, 50",
        "jobs_product_code": "JOB_AD_CHAPT_NE",
        "job_post_instruction_code": "NE_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_NE",
        "directory_code": "DIRECTORY_NE",
        "favicon": "component-sites/image/nebraska/favicon.ico",
        "facebook": "apanebraska",
        "youtube": "",
        "twitter": "apa_nebraska",
        "instagram": "",
        "linkedin": "groups/6735065/",
        "admin_group": "CHAPT_NE-admin"
    },

    "nne.planning.org": {
        "site": "nne.planning.org",
        "verbose_name": "Northern New England",
        "static":"nne",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/nne/NNE_logo_569.png",
        "logo_signature": "component-sites/image/nne/NNE_horizontal_569.png",
        "username": "190099",
        "addl_providers": "",
        "color": "0, 127, 110",
        "jobs_product_code": "JOB_AD_CHAPT_NNE",
        "job_post_instruction_code": "NNE_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_NNE",
        "directory_code": "DIRECTORY_NNE",
        "favicon": "component-sites/image/nne/favicon.ico",
        "facebook": "",
        "youtube": "",
        "twitter": "",
        "instagram": "",
        "linkedin": "",
        "admin_group":"CHAPT_NNE-admin"
    },

    "privatepractice.planning.org": {
        "site": "privatepractice.planning.org",
        "verbose_name": "Private Practice",
        "type": "DIVISION",
        "logo_block": "component-sites/image/privatepractice/PrivatePractice_647+7447.png",
        "logo_signature": "component-sites/image/privatepractice/PrivatePractice_horizontal_647+7447.png",
        "username": "214709",
        "addl_providers": "",
        "tag_code": "PRIVATE",
        "color": "95, 71, 118",
        "jobs_product_code": "JOB_AD_PRIVATE",
        "job_post_instruction_code": "PRIVATE_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_PRIVATE",
        "directory_code": "DIRECTORY_PRIVATE",
        "favicon": "component-sites/image/privatepractice/favicon.ico",
        "facebook": "APAPrivatePractice",
        "youtube": "",
        "twitter": "",
        "instagram": "",
        "linkedin": "groups?home=&gid=4739366&trk=anet_ug_hm",
        "admin_group": "PRIVATE-admin"
    },

    "tech.planning.org": {
        "site": "tech.planning.org",
        "verbose_name": "Technology",
        "type": "DIVISION",
        "logo_block": "component-sites/image/technology/Tech_647+397.png",
        "logo_signature":"component-sites/image/technology/Tech_horizontal_647+397.png",
        "username": "227138",
        "addl_providers": "",
        "tag_code": "TECHNOLOGY",
        "color": "203, 151, 0",
        "jobs_product_code": "JOB_AD_TECH",
        "job_post_instruction_code": "TECH_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_TECH",
        "directory_code": "DIRECTORY_PRIVATE",
        "favicon": "component-sites/image/technology/favicon.ico",
        "facebook": "pages/apa-technology/218923968143539",
        "youtube": "user/apatechnology",
        "twitter": "APA_Technology",
        "linkedin": "groups?gid=4409686",
        "admin_group": "TECH-admin"
    },

    "tennessee.planning.org": {
        "site": "tennessee.planning.org",
        "verbose_name": "Tennessee",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/tennessee/TN_logo_363.png",
        "logo_signature": "component-sites/image/tennessee/TN_horizontal_363.png",
        "username": "159611",
        "addl_providers": "",
        "color": "128, 188, 0",
        "jobs_product_code": "JOB_AD_CHAPT_TN",
        "job_post_instruction_code": "TN_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_TN",
        "directory_code": "DIRECTORY_TN",
        "favicon": "component-sites/image/tennessee/favicon.ico",
        "facebook": "",
        "youtube": "",
        "twitter": "",
        "instagram": "",
        "linkedin": "",
        "admin_group": "CHAPT_TN-admin"
    },

    "texas.planning.org": {
        "site": "texas.planning.org",
        "verbose_name": "Texas",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/texas/TX_logo_634.png",
        "logo_signature": "component-sites/image/texas/TX_horizontal_634.png",
        "username": "159573",
        "addl_providers": "",
        "color": "0, 145, 179",
        "jobs_product_code": "JOB_AD_CHAPT_TX",
        "job_post_instruction_code": "TX_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_TX",
        "directory_code": "DIRECTORY_TX",
        "favicon": "component-sites/image/texas/favicon.ico",
        "facebook": "txplanning",
        "youtube": "channel/UCj0JRgeaxx8my1fbfomBpKA",
        "twitter": "txplanning",
        "instagram": "txplanning",
        "linkedin": "txplanning",
        "admin_group": "CHAPT_TX-admin"
    },

    "transportation.planning.org": {
        "site": "transportation.planning.org",
        "verbose_name": "Transportation",
        "type": "DIVISION",
        "logo_block": "component-sites/image/transportation/Transport_647+7467.png",
        "logo_signature": "component-sites/image/transportation/Transport_horizontal_647+7467.png",
        "username": "184884",
        "addl_providers": "",
        "tag_code": "TRANSPORTATION",
        "color": "0, 162, 174",
        "jobs_product_code": "JOB_AD_TRANS",
        "job_post_instruction_code": "TRANS_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_TRANS",
        "directory_code": "DIRECTORY_TRANS",
        "favicon": "component-sites/image/transportation/favicon.ico",
        "facebook": "groups/41884958915",
        "youtube": "",
        "twitter": "apatpd",
        "instagram": "apatpd",
        "linkedin": "groups/1178607",
        "admin_group": "TRANS-admin"
    },

    "urbandesign.planning.org": {
        "site": "urbandesign.planning.org",
        "verbose_name": "Urban Design",
        "static": "urban-design",
        "type": "DIVISION",
        "logo_block": "component-sites/image/urban-design/UrbanDesign_647+7408.png",
        "logo_signature": "component-sites/image/urban-design/UrbanDesign_horizontal_647+7408.png",
        "username": "184881",
        "addl_providers": "",
        "tag_code": "URBAN_DESIGN",
        "color": "249, 190, 0",
        "jobs_product_code": "JOB_AD_URBAN_DES",
        "job_post_instruction_code": "UD_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_URBAN_DES",
        "directory_code": "DIRECTORY_URBAN_DES",
        "favicon": "component-sites/image/urban-design/favicon.ico",
        "facebook": "APA-Urban-Design-and-Preservation-Division-108674005169",
        "youtube": "",
        "twitter": "APAUDP",
        "instagram": "apaudp",
        "linkedin": "groups/1993322",
        "admin_group": "URBAN_DES-admin"
    },

    "virginia.planning.org": {
        "site": "virginia.planning.org",
        "verbose_name": "Virginia",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/virginia/VA_logo_506.png",
        "logo_signature": "component-sites/image/virginia/VA_horizontal_506.png",
        "username": "136431",
        "addl_providers": "",
        "color": "137, 37, 40",
        "jobs_product_code": "JOB_AD_CHAPT_VA",
        "job_post_instruction_code": "VA_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_VA",
        "directory_code": "DIRECTORY_CHAPT_VA",
        "favicon": "component-sites/image/virginia/favicon.ico",
        "facebook": "APAVirginia",
        "youtube": "channel/UCGrer-HWpjrwZ9ROKVc8HtA",
        "twitter": "APA_Virginia",
        "instagram": "apa_virginia",
        "linkedin": "groups/2382200",
        "admin_group": "CHAPT_VA-admin"
    },

    "wcc.planning.org": {
        "site": "wcc.planning.org",
        "verbose_name": "Western Central",
        "static": "wcc",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/wcc/WC_logo_397.png",
        "logo_signature": "component-sites/image/wcc/WC_horizontal_397.png",
        "username": "189862",
        "addl_providers": "",
        "color": "207, 180, 0",
        "jobs_product_code": "JOB_AD_CHAPT_WC",
        "job_post_instruction_code": "WCC_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_WC",
        "directory_code": "DIRECTORY_WCC",
        "favicon": "component-sites/image/wcc/favicon.ico",
        "facebook": "",
        "youtube": "",
        "twitter": "WestCentralChap",
        "instagram": "westerncentralchapter",
        "linkedin": "",
        "admin_group":"-admin"
    },
    "wisconsin.planning.org": {
        "site": "wisconsin.planning.org",
        "verbose_name": "Wisconsin",
        "type": "CHAPTER",
        "logo_block": "component-sites/image/wisconsin/WI_logo_363.jpg",
        "logo_signature": "component-sites/image/wisconsin/WI_horizontal_363.png",
        "username": "172946",
        "addl_providers": "",
        "color": "61, 142, 51",
        "jobs_product_code": "JOB_AD_CHAPT_WI",
        "job_post_instruction_code": "WI_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_CHAPT_WI",
        "directory_code": "DIRECTORY_CHAPT_WI",
        "favicon": "component-sites/image/wisconsin/favicon.ico",
        "facebook": "apawisconsin",
        "youtube": "",
        "twitter": "apa_wi",
        "instagram": "",
        "linkedin": "",
        "admin_group":"CHAPT_WI-admin"
    },

    "women.planning.org": {
        "site": "women.planning.org",
        "verbose_name": "Women",
        "type": "DIVISION",
        "logo_block": "component-sites/image/women/women_647+606.png",
        "logo_signature": "component-sites/image/women/women_horizontal_647+606.png",
        "username": "214714",
        "addl_providers": "",
        "tag_code": "WOMEN",
        "color": "242, 205, 0",
        "jobs_product_code": "JOB_AD_WOMEN",
        "job_post_instruction_code": "WOMEN_JOB_POST_INSTRUCTIONS",
        "job_submission_category_code": "JOB_AD_WOMEN",
        "directory_code": "DIRECTORY_WOMEN",
        "favicon": "component-sites/image/women/favicon.ico",
        "facebook": "groups/APAPWD",
        "youtube": "",
        "twitter": "APAPWD",
        "instagram": "",
        "linkedin": "groups/5103501",
        "admin_group":"WOMEN-admin"
    },

}
