# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('comments', '0001_initial'), ('comments', '0002_auto_20151001_1815'), ('comments', '0003_auto_20151105_1747'), ('comments', '0004_auto_20160705_2112'), ('comments', '0005_eventcomment')]

    initial = True

    dependencies = [
        # ('content', '0001_squashed_0012_auto_20161018_1735'),
        ('content', '0001_squashed_0064_auto_20160328_1819'),
        # ('myapa', '0004_contact_company_fk'),
        # ('myapa', '0001_squashed_0007_auto_20161018_1735'),
('myapa', '0001_squashed_0052_auto_20160331_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('STORE_REVIEW', 'Product Review'), ('CONTENT', 'General Comments on Content'), ('CM', 'CM Log Comments and Ratings'), ('EVENT_EVAL', 'Event Evaluations'), ('SPEAKER_EVAL', 'Speaker Evaluations')], default='CONTENT', max_length=50)),
                ('submitted_time', models.DateTimeField(editable=False)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapa.Contact')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.Content')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='contactrole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapa.ContactRole'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.Content'),
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('comments.comment',),
        ),
    ]
