# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170410_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedeventevaluation',
            name='commentary_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedeventevaluation',
            name='commentary_takeaways',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('STORE_REVIEW', 'Product Review'), ('CONTENT', 'General Comments on Content'), ('CM', 'CM Log Comments and Ratings'), ('EVENT_EVAL', 'Event Evaluations'), ('LEARN_COURSE', 'APA Learn Course Eval/Completion'), ('LEARN_SPEAKER', 'APA Learn Speaker Eval/Completion'), ('SPEAKER_EVAL', 'Speaker Evaluations')], default='CONTENT', max_length=50),
        ),
    ]
