# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-07 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0007_auto_20190729_1623'),
        ('comments', '0004_auto_20190314_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedspeakerevaluation',
            name='comment_ptr',
        ),
        migrations.DeleteModel(
            name='ExtendedSpeakerEvaluation',
        ),
    ]
