# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-24 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20191217_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedeventevaluation',
            name='knowledge_rating',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], null=True),
        ),
        migrations.AddField(
            model_name='extendedeventevaluation',
            name='practice_rating',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], null=True),
        ),
        migrations.AddField(
            model_name='extendedeventevaluation',
            name='speaker_rating',
            field=models.IntegerField(choices=[('N/A', 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], null=True),
        ),
        migrations.AlterField(
            model_name='extendedeventevaluation',
            name='objective_rating',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], null=True),
        ),
        migrations.AlterField(
            model_name='extendedeventevaluation',
            name='value_rating',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], null=True),
        ),
    ]
