# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20191217_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contactrole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='myapa.ContactRole'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='content.Content'),
        ),
    ]
