# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20200225_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedeventevaluation',
            name='speaker_rating',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], null=True),
        ),
    ]
