# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-24 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20200415_0854'),
        ('comments', '0007_auto_20200324_1614'),
    ]

    operations = [
    ]
