# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('pages', '0001_squashed_0007_auto_20160314_0648'), ('pages', '0002_auto_20160601_2348')]

    initial = True

    dependencies = [
        # ('content', '0001_squashed_0012_auto_20161018_1735'),
        ('content', '0001_squashed_0064_auto_20160328_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'all pages',
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='AICPPage',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'AICP page',
            },
            bases=('pages.page',),
        ),
        # migrations.CreateModel(
        #     name='ResearchPage',
        #     fields=[
        #     ],
        #     options={
        #         'proxy': True,
        #     },
        #     bases=('pages.page',),
        # ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'About APA page',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='CareerPage',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Career center page',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='ConferencesPage',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Conferences/meetings page',
                'verbose_name_plural': 'Conferences and meetings pages',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='ConnectPage',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Connect with APA page',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='KnowledgeCenterPage',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Knowledge center page',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='MembershipPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='OutreachPage',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Community outreach page',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Policy/advocacy page',
                'verbose_name_plural': 'Policy and advocacy pages',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='UncategorizedPage',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': '**Uncategorized page',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('search_query', models.TextField(blank=True, help_text='The query to pull records from the search. Work with IT to populate this field appropriately.', null=True)),
                ('sort_field', models.CharField(blank=True, choices=[('sort_time desc', 'Time descending'), ('sort_time asc', 'Time ascending'), ('title', 'Title'), ('', 'Relevancy')], default='sort_time desc', max_length=50)),
                ('search_max', models.IntegerField(default=20)),
                ('show_search_results', models.BooleanField(default=False, help_text='Include dynamic search results on this landing page?')),
            ],
            options={
                'proxy': False,
                'verbose_name': 'section overview or landing page',
                'verbose_name_plural': 'section overview and landing pages',
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='LandingPageMasterContent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('content.mastercontent',),
        ),
        # migrations.DeleteModel(
        #     name='ResearchPage',
        # ),
        # migrations.AlterModelOptions(
        #     name='knowledgecenterpage',
        #     options={'verbose_name': 'Knowledge center page'},
        # ),
    ]
