# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_squashed_0002_auto_20160601_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpage',
            options={'verbose_name': 'landing page'},
        ),
    ]
