# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-13 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170111_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPage',
            fields=[
            ],
            options={
                'verbose_name': 'Searchable Media - Audio page',
                'proxy': True,
                'indexes': [],
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='VideoPage',
            fields=[
            ],
            options={
                'verbose_name': 'Searchable Media - Video page',
                'proxy': True,
                'indexes': [],
            },
            bases=('pages.page',),
        ),
    ]
