# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-09-03 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190613_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='JotFormPage',
            fields=[
            ],
            options={
                'verbose_name': 'JotForm page',
                'proxy': True,
                'indexes': [],
            },
            bases=('pages.page',),
        ),
    ]
