# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_squashed_0005_auto_20160804_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
