# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20180411_2242'),
        ('pages', '0002_auto_20170111_1653'),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_npc', models.BooleanField(default=False, verbose_name='Is NPC')),
                ('short_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short title')),
                ('url_path_stem', models.CharField(default='conference', max_length=50, verbose_name='Microsite identifier')),
                ('home_page_code', models.CharField(default='CONFERENCE_HOME', max_length=50, verbose_name='Microsite home page code')),
                ('show_skip_to_dates', models.BooleanField(default=True, verbose_name='Show skip to dates')),
                ('status', models.CharField(default='A', max_length=5, verbose_name='microsite status')),
                ('deactivation_date', models.DateTimeField(blank=True, null=True, verbose_name='Deactivation date')),
                ('header_ad', models.TextField(blank=True, null=True, verbose_name='Microsite header ad html')),
                ('sidebar_ad', models.TextField(blank=True, null=True, verbose_name='Microsite sidebar ad html')),
                ('footer_ad', models.TextField(blank=True, null=True, verbose_name='Microsite footer ad html')),
                ('custom_color', models.CharField(blank=True, help_text='hex value of conference microsite custom color', max_length=50, null=True)),
                ('hero_image_path', models.CharField(default='newtheme/image/conference-hero-bg.jpg', max_length=100)),
                ('home_summary_blurb', models.TextField(blank=True, null=True, verbose_name='Microsite summary html blurb')),
                ('signpost_logo_image_path', models.CharField(default='newtheme/image/npc-sign.png', max_length=100)),
                ('program_blurb', models.TextField(blank=True, null=True, verbose_name='Program html blurb')),
                ('nosidebar_breakout_image_path', models.CharField(default='newtheme/image/content-header-conference-image-breakout-default.jpg', max_length=100)),
                ('details_inclusive_blurb', models.TextField(blank=True, null=True, verbose_name='Inclusiveness/Social Justice html blurb')),
                ('details_local_blurb', models.TextField(blank=True, null=True, verbose_name='Local/Regional html blurb')),
                ('event_master', models.ForeignKey(blank=True, help_text='Event associated with microsite', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_microsite', to='content.MasterContent')),
                ('home_page', models.ForeignKey(blank=True, help_text='The page that holds the top bar mega menu nav', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_microsite', to='pages.LandingPageMasterContent', verbose_name='Microsite home page')),
                ('search_filters', models.ForeignKey(blank=True, help_text='The search filters for the microsite', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microsite', to='content.TagType', verbose_name='Microsite search filters')),
            ],
        ),
    ]
