# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0016_auto_20180327_2139'),
        ('events', '0011_auto_20180327_2139'),
        ('registrations', '0001_squashed_0008_auto_20160328_1722'),
        ('conference', '0002_microsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrositeActivity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Microsite Activities',
                'proxy': True,
                'indexes': [],
                'verbose_name': 'Microsite Activity',
            },
            bases=('events.activity',),
        ),
        migrations.CreateModel(
            name='MicrositeAttendee',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Microsite Attendees',
                'proxy': True,
                'indexes': [],
                'verbose_name': 'Microsite Attendee',
            },
            bases=('registrations.attendee',),
        ),
        migrations.CreateModel(
            name='MicrositeContributor',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'verbose_name': 'Microsite Event Contributor',
            },
            bases=('myapa.contactrole',),
        ),
        migrations.CreateModel(
            name='NationalConferenceAttendee',
            fields=[
            ],
            options={
                'verbose_name_plural': 'NPC Attendees',
                'proxy': True,
                'indexes': [],
                'verbose_name': 'NPC Attendee',
            },
            bases=('registrations.attendee',),
        ),
        migrations.CreateModel(
            name='NationalConferenceContributor',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'verbose_name': 'Conference Participant',
            },
            bases=('myapa.contactrole',),
        ),
        migrations.CreateModel(
            name='NationalConferenceActivity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'NPC Activities',
                'proxy': True,
                'indexes': [],
                'verbose_name': 'NPC Activity',
            },
            bases=('conference.micrositeactivity',),
        ),
    ]
