# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_micrositeactivity_micrositeattendee_micrositecontributor_nationalconferenceactivity_nationalconferen'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='ConferenceActivity',
        # ),
        migrations.DeleteModel(
            name='ConferenceAttendee',
        ),
        migrations.DeleteModel(
            name='ConferenceContact',
        ),
        # migrations.DeleteModel(
        #     name='ConferenceParticipant',
        # ),
    ]
