# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20180411_2242'),
        ('conference', '0004_auto_20180606_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsite',
            name='program_search_filters',
            field=models.ManyToManyField(blank=True, help_text='The search filters for the microsite', related_name='micro_site', to='content.TagType', verbose_name='Microsite search filters'),
        ),
    ]
