# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20181113_1509'),
        ('conference', '0005_microsite_program_search_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrositeEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Microsite event',
                'verbose_name_plural': 'Microsite events',
                'proxy': True,
                'indexes': [],
            },
            bases=('events.eventmulti',),
        ),
        migrations.AddField(
            model_name='microsite',
            name='interactive_educational_session',
            field=models.TextField(blank=True, null=True, verbose_name='Interactive Educational Session html blurb'),
        ),
        migrations.CreateModel(
            name='NationalConferenceEvent',
            fields=[
            ],
            options={
                'verbose_name': 'National Planning Conference',
                'verbose_name_plural': 'National Planning Conferences',
                'proxy': True,
                'indexes': [],
            },
            bases=('conference.micrositeevent',),
        ),
    ]
