# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-01 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_auto_20181218_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadmiumMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(blank=True, choices=[('HARVESTER_ROLE_TO_DJANGO_ROLE', 'Harvester Speaker Role to Django Role Type'), ('HARVESTER_ROOM_TITLE_TO_CODE', 'Harvester Room to Django Room Tag'), ('HARVESTER_SESSION_TYPE_TO_ACTIVITY_TYPE', 'Harvester Session Type to Django Activity Type'), ('HARVESTER_TRACK_TO_APA_CODE', 'Harvester Track to Django Track Tag'), ('HARVESTER_TOPICS_TO_APA_TAXO', 'Harvester Topics to Django Taxonomy Tags'), ('PRESENTATION_FIELD_TO_POSTGRES_FIELD', 'Harester Presentation Field to Django Field'), ('PRESENTER_FIELD_TO_POSTGRES_FIELD', 'Harester Presenter Field to Django Field'), ('CUSTOM_PRES_FIELD_TO_POSTGRES_FIELD', 'Harvester Presentation Custom Field to Django Field'), ('PRESENTER_CUSTOM_FIELD_TO_POSTGRES_FIELD', 'Harvester Presenter Custom Field to Django Field'), ('', '')], max_length=100, null=True)),
                ('from_string', models.CharField(blank=True, max_length=200, null=True)),
                ('to_string', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CadmiumSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadmium_event_key', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('registration_task_id', models.CharField(blank=True, max_length=20, null=True)),
                ('endpoint', models.URLField(blank=True, max_length=255, null=True)),
                ('microsite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadmium_sync', to='conference.Microsite')),
            ],
        ),
        migrations.AddField(
            model_name='cadmiummapping',
            name='cadmium_sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadmium_mappings', to='conference.CadmiumSync'),
        ),
    ]
