# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-16 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_microsite_text_blurb_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsite',
            name='details_inclusive_blurb',
        ),
    ]
