# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_auto_20191001_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmiumsync',
            name='parent_landing_master_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadmiummapping',
            name='mapping_type',
            field=models.CharField(blank=True, choices=[('HARVESTER_ROLE_TO_DJANGO_ROLE', 'Harvester Speaker Role to Django Role Type'), ('HARVESTER_ROOM_TITLE_TO_CODE', 'Harvester Room to Django Room Tag'), ('HARVESTER_SESSION_TYPE_TO_ACTIVITY_TYPE', 'Harvester Session Type to Django Activity Type'), ('HARVESTER_TRACK_TO_APA_CODE', 'Harvester Track to Django Track Tag'), ('HARVESTER_TOPICS_TO_APA_TAXO', 'Harvester Topics to Django Taxonomy Tags'), ('PRESENTATION_FIELD_TO_POSTGRES_FIELD', 'Harester Presentation Field to Django Field'), ('PRESENTER_FIELD_TO_POSTGRES_FIELD', 'Harester Presenter Field to Django Field'), ('CUSTOM_PRES_FIELD_TO_POSTGRES_FIELD', 'Harvester Presentation Custom Field to Django Field'), ('PRESENTER_CUSTOM_FIELD_TO_POSTGRES_FIELD', 'Harvester Presenter Custom Field to Django Field')], max_length=100, null=True),
        ),
    ]
