# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_auto_20191002_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmiumsync',
            name='activity_tag_type_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cadmiumsync',
            name='division_tag_type_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cadmiumsync',
            name='npc_category_tag_type_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cadmiumsync',
            name='track_tag_type_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cadmiummapping',
            name='cadmium_sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadmium_mappings', to='conference.CadmiumSync'),
        ),
        migrations.AlterField(
            model_name='cadmiummapping',
            name='mapping_type',
            field=models.CharField(blank=True, choices=[('HARVESTER_ROLE_TO_DJANGO_ROLE', 'Harvester Speaker Role to Django Role Type'), ('HARVESTER_SESSION_TYPE_TO_ACTIVITY_TYPE', 'Harvester Session Type to Django Activity Type'), ('HARVESTER_TRACK_TO_APA_CODE', 'Harvester Track to Django Track Tag'), ('HARVESTER_TOPICS_TO_APA_TAXO', 'Harvester Topics to Django Taxonomy Tags'), ('PRESENTATION_FIELD_TO_POSTGRES_FIELD', 'Harvester Presentation Field to Django Field'), ('PRESENTER_FIELD_TO_POSTGRES_FIELD', 'Harvester Presenter Field to Django Field'), ('CUSTOM_PRES_FIELD_TO_POSTGRES_FIELD', 'Harvester Presentation Custom Field to Django Field'), ('PRESENTER_CUSTOM_FIELD_TO_POSTGRES_FIELD', 'Harvester Presenter Custom Field to Django Field')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadmiumsync',
            name='microsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadmium_sync', to='conference.Microsite'),
        ),
    ]
