# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-04 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_auto_20191002_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadmiummapping',
            name='mapping_type',
            field=models.CharField(blank=True, choices=[('HARVESTER_ROLE_TO_DJANGO_ROLE', 'Harvester Speaker Role to Django Role Type'), ('HARVESTER_SESSION_TYPE_TO_ACTIVITY_TYPE', 'Harvester Session Type to Django Activity Type'), ('HARVESTER_TRACK_TO_APA_CODE', 'Harvester Track to Django Track Tag'), ('HARVESTER_TOPICS_TO_APA_TAXO', 'Harvester Topics to Django Taxonomy Tags'), ('PRESENTATION_FIELD_TO_POSTGRES_FIELD', 'Presentation Field to Django'), ('PRESENTER_FIELD_TO_POSTGRES_FIELD', 'Presenter Field to Django'), ('CUSTOM_PRES_FIELD_TO_POSTGRES_FIELD', 'Presentation Custom Field to Django'), ('PRESENTER_CUSTOM_FIELD_TO_POSTGRES_FIELD', 'Presenter Custom Field to Django')], max_length=100, null=True),
        ),
    ]
