# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_auto_20191004_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmiummapping',
            name='cadmium_syncs',
            field=models.ManyToManyField(blank=True, related_name='mappings', to='conference.CadmiumSync'),
        ),
    ]
