# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-08 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_cadmiummapping_cadmium_syncs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cadmium Sync Mapping',
                'verbose_name_plural': 'Cadmium Sync Mappings',
            },
        ),
        migrations.AlterField(
            model_name='cadmiummapping',
            name='cadmium_syncs',
            field=models.ManyToManyField(blank=True, related_name='harvester_mappings', to='conference.CadmiumSync'),
        ),
        migrations.AddField(
            model_name='syncmapping',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.CadmiumMapping'),
        ),
        migrations.AddField(
            model_name='syncmapping',
            name='sync',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.CadmiumSync'),
        ),
        migrations.AddField(
            model_name='cadmiumsync',
            name='mappings',
            field=models.ManyToManyField(related_name='harvester_syncs', through='conference.SyncMapping', to='conference.CadmiumMapping'),
        ),
    ]
