# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-09 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_auto_20191008_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadmiummapping',
            name='cadmium_sync',
        ),
        migrations.RemoveField(
            model_name='cadmiummapping',
            name='cadmium_syncs',
        ),
    ]
