# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-17 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_auto_20191009_1248'),
        ('conference', '0008_remove_microsite_details_inclusive_blurb'),
    ]

    operations = [
    ]
