# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-02-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_auto_20200324_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsite',
            name='internal_footer_ad',
            field=models.TextField(blank=True, null=True, verbose_name='Microsite internal footer ad html'),
        ),
        migrations.AddField(
            model_name='microsite',
            name='internal_header_ad',
            field=models.TextField(blank=True, null=True, verbose_name='Microsite internal header ad html'),
        ),
        migrations.AddField(
            model_name='microsite',
            name='internal_interstitial_ad',
            field=models.TextField(blank=True, null=True, verbose_name='Microsite internal interstitial ad html'),
        ),
        migrations.AddField(
            model_name='microsite',
            name='internal_sidebar_ad',
            field=models.TextField(blank=True, null=True, verbose_name='Microsite internal sidebar ad html'),
        ),
        migrations.AddField(
            model_name='microsite',
            name='interstitial_ad',
            field=models.TextField(blank=True, null=True, verbose_name='Microsite interstitial ad html'),
        ),
    ]
