# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('support', '0001_squashed_0009_auto_20160223_2308'), ('support', '0002_auto_20160601_2336'), ('support', '0003_auto_20161018_1735')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('myapa', '0001_squashed_0007_auto_20161018_1735'),
('myapa', '0001_squashed_0052_auto_20160331_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='An identifier for the ending of the url - will be auto-generated based on the title for web pages.', null=True)),
                ('created_time', models.DateTimeField(editable=False)),
                ('updated_time', models.DateTimeField(editable=False)),
                ('apa_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='APA ID #')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='myapa.Contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket_updated_by', to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(choices=[('AICP', 'AICP Certification Exam'), ('BOOKSTORE', 'APA Bookstore'), ('LIBRARY', 'APA Library'), ('CONTACT', 'APA Phone, Addresses, Fax, email'), ('WEBSITE', 'APA Website'), ('ASC', 'Advanced Specialty Certification (ASC)'), ('CM', 'Certification Maintenance'), ('CM_SPEAKERS', 'CM Speakers'), ('CPAT', 'Community Planning Assistance (CPAT)'), ('EARLY_CAREER', 'Early Career Membership Program'), ('ETHICS', 'Ethics'), ('FAICP', 'Fellows of AICP (FAICP)'), ('VOLUNTEER', 'Get Involved/Volunteer'), ('GREAT_PLACES', 'Great Places in America'), ('JOBS', 'Jobs Online'), ('JOIN', 'Join APA'), ('MEMBERSHIP', 'Membership'), ('AWARDS', 'National Planning Awards'), ('NPC', 'National Planning Conference'), ('PAS', 'Planning Advisory Service (PAS)'), ('OTHER', 'Other')], max_length=50)),
                ('ticket_status', models.CharField(choices=[('S', 'Submitted'), ('P', 'Pending'), ('IT', 'Tech Issue - Handed Over to IT Support'), ('C', 'Complete')], default='S', max_length=5)),
                ('staff_comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'support ticket',
                'abstract': False,
            },
        ),
    ]
