# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_squashed_0003_auto_20161018_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('ASC', 'Advanced Specialty Certification (ASC)'), ('AICP', 'AICP Certification Exam'), ('LIBRARY', 'APA Library'), ('FOUNDATION', 'APA Foundation and Scholarships'), ('CAREER', 'Career Services'), ('CM', 'Certification Maintenance'), ('CM_SPEAKERS', 'CM Speakers'), ('CPAT', 'Community Planning Assistance (CPAT)'), ('ETHICS', 'Ethics'), ('FAICP', 'Fellows of AICP (FAICP)'), ('GREAT_PLACES', 'Great Places in America'), ('JOBS', 'Jobs Online/ RFPs and RFQs'), ('MEMBERSHIP', 'Membership'), ('AWARDS', 'National Planning Awards'), ('NPC', 'National Planning Conference'), ('PAS', 'PAS / Inquiry Answering Service'), ('EARLY_CAREER', 'Student Membership'), ('CONTACT', 'Update MyAPA Info. (email, phone, address)'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
