# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20170921_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('ASC', 'AICP Advanced Specialty Certification (ASC)'), ('AICP', 'AICP Certification Exam'), ('LIBRARY', 'APA Library'), ('FOUNDATION', 'APA Foundation and Scholarships'), ('CAREER', 'Career Services'), ('CM', 'AICP Certification Maintenance'), ('CM_SPEAKERS', 'AICP CM Speakers'), ('CPAT', 'Community Planning Assistance (CPAT)'), ('ETHICS', 'Ethics'), ('FAICP', 'AICP Fellows (FAICP)'), ('GREAT_PLACES', 'Great Places in America'), ('JOBS', 'Jobs Online/ RFPs and RFQs'), ('MEMBERSHIP', 'Membership'), ('AWARDS', 'National Planning Awards'), ('NPC', 'National Planning Conference'), ('PAS', 'PAS / Inquiry Answering Service'), ('EARLY_CAREER', 'Student Membership'), ('CONTACT', 'Update MyAPA Info. (email, phone, address)'), ('OTHER', 'Other'), ('CONSULTANTS_ADVERTISING', 'Consultants/Advertising'), ('AICP_CANDIDATE_PROGRAM', 'AICP Candidate Program'), ('APA_LEARN', 'APALearn')], max_length=50),
        ),
    ]
