# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20180713_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('S', 'Submitted'), ('P', 'Pending'), ('IT', 'Tech Issue - Handed Over to IT Support'), ('C', 'Complete'), ('SP', 'Spam')], default='S', max_length=5),
        ),
    ]
