# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('directories', '0001_squashed_0008_auto_20160401_1553'), ('directories', '0002_auto_20161018_1735')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('store', '0001_squashed_0007_auto_20161018_1734'),
('store', '0001_squashed_0041_auto_20160312_0447'),
        ('auth', '0001_initial'),
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='An identifier for the ending of the url - will be auto-generated based on the title for web pages.', null=True)),
                ('created_time', models.DateTimeField(editable=False)),
                ('updated_time', models.DateTimeField(editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories_directory_created_by', to=settings.AUTH_USER_MODEL)),
                ('permission_groups', models.ManyToManyField(blank=True, help_text='Permission groups for those able to view the directory', null=True, to='auth.Group')),
                ('subscription_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='store.Product')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories_directory_updated_by', to=settings.AUTH_USER_MODEL)),
                ('directory_group', models.ForeignKey(blank=True, help_text='Permission group for those to be INCLUDED in the directory (optional, e.g. for rosters)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='included_in_directories', to='auth.Group')),
            ],
            options={
                'verbose_name_plural': 'Directories',
            },
        ),
    ]
