# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_squashed_0002_auto_20161018_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='directory_group',
            field=models.ForeignKey(blank=True, help_text='Permission group for those to be INCLUDED in the directory                    (optional, e.g. for rosters)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='included_in_directories', to='auth.Group'),
        ),
    ]
