# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_auto_20170202_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='committees',
            field=models.CharField(blank=True, help_text='Committee codes to include in the directory. Separate multiple values by commas, without spaces.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='directory_group',
            field=models.ForeignKey(blank=True, help_text='Permission group for those to be INCLUDED in the directory (may be depreciated)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='included_in_directories', to='auth.Group'),
        ),
    ]
