# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-24 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_auto_20190711_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directories_directory_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directory',
            name='directory_group',
            field=models.ForeignKey(blank=True, help_text='Permission group for those to be INCLUDED in the directory (may be depreciated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='included_in_directories', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directories_directory_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
