# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 21:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    # replaces = [('cm', '0001_squashed_0029_auto_20160223_2308'), ('cm', '0002_claim_is_pro_bono'), ('cm', '0003_claim_learning_objectives'), ('cm', '0004_auto_20160705_2057'), ('cm', '0005_claim_timezone'), ('cm', '0006_auto_20161017_1121'), ('cm', '0007_auto_20161018_1735'), ('cm', '0008_auto_20161122_1602')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('events', '0001_squashed_0005_event_ticket_template'),
('events', '0001_squashed_0020_event_length_in_minutes'),
        ('comments', '0001_squashed_0005_eventcomment'),
        # ('myapa', '0001_squashed_0007_auto_20161018_1735'),
('myapa', '0001_squashed_0052_auto_20160331_1650'),
        # ('store', '0001_squashed_0007_auto_20161018_1734'),
('store', '0001_squashed_0041_auto_20160312_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMComment',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'CM Rating/Comment',
            },
            bases=('comments.comment',),
        ),
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain_topics', models.TextField(blank=True, null=True)),
                ('objectives_status', models.CharField(blank=True, choices=[('ALWAYS', 'Always'), ('SOMETIMES', 'Sometimes'), ('NEVER', 'Never')], max_length=50, null=True)),
                ('objectives_example_1', models.TextField(blank=True, null=True)),
                ('objectives_example_2', models.TextField(blank=True, null=True)),
                ('how_determines_speakers', models.TextField(blank=True, null=True)),
                ('evaluates_activities', models.BooleanField(default=False)),
                ('evaluation_procedures', models.TextField(blank=True, null=True)),
                ('agree_keep_records', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='myapa.Contact')),
                ('status', models.CharField(choices=[('A', 'Approved'), ('D', 'Deferred'), ('S', 'Submitted'), ('I', 'Incomplete')], default='S', max_length=50)),
                ('submitted_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Submitted date')),
                ('year', models.IntegerField(default=None)),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='Approval window begin')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Approval window end')),
                ('intended_registration_type', models.CharField(choices=[('CM_PER_CREDIT', 'Per-Credit'), ('CM_UNLIMITED_1', 'Annual Unlimited - Government and University Rate : $1,995 + $95 registration fee'), ('CM_UNLIMITED_INHOUSE', 'In House Annual Unlimited (for employee training only) : $475 + $95 registration fee'), ('CM_UNLIMITED_NONPROFIT_1', 'Annual Unlimited (nonprofit, less than $500,000) : $945 + $95 registration fee'), ('CM_UNLIMITED_NONPROFIT_2', 'Annual Unlimited (nonprofit, $500,000 to $5M) : $1,995 + $95 registration fee'), ('CM_UNLIMITED_NONPROFIT_3', 'Annual Unlimited (nonprofit, $5M to 15M) : $2,995 + $95 registration fee'), ('CM_UNLIMITED_NONPROFIT_4', 'Annual Unlimited (nonprofit, over $15M) : $5,145 + $95 registration fee'), ('CM_UNLIMITED_PARTNER', 'Unlimited registration through partner organization : $95'), ('CM_UNLIMITED_SMALL', 'For-Profit and Not-for-Profit Providers with gross revenue < $500K : $1,254'), ('CM_UNLIMITED_MEDIUM', 'Universities and  Governments - For-Profit and Not-for-Profit Providers with gross revenue $500K−$5M : $2,461 '), ('CM_UNLIMITED_LARGE', 'For-Profit and Not-for-Profit Providers with gross revenue $5M−$15M : $3,611 '), ('CM_UNLIMITED_LARGEST', 'For-Profit and Not-for-Profit Providers with gross revenue > $15M : $6,084 ')], default='A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('law_credits', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ethics_credits', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_speaker', models.BooleanField(default=False)),
                ('is_author', models.BooleanField(default=False)),
                ('self_reported', models.BooleanField(default=False)),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_claim', to='cm.CMComment')),
                ('is_carryover', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=80, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('begin_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_claims', to='events.Event')),
                ('contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_claims', to='myapa.Contact')),
                ('is_pro_bono', models.BooleanField(default=False)),
                ('learning_objectives', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, help_text='The timezone for the location of the event', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('G', 'In Grace Period'), ('R', 'Reinstatement'), ('C', 'Completed and Closed'), ('E_01', 'Exempt - Retired;'), ('E_02', 'Exempt - Unemployed members'), ('E_03', 'Exempt - Planners practicing outside of U.S.'), ('E_06', 'Exempt - Parental leave'), ('E_07', 'Exempt - Military service leave'), ('E_09', 'Exempt - Health leave'), ('E_10', 'Exempt - Care leave'), ('E_11', 'Exempt - Foreign residency'), ('E_12', 'Exempt - Other (case-by-case)'), ('E_13', 'Exempt - Voluntary Life option'), ('D', 'Dropped'), ('RA', 'Reinstatement Amnesty')], default='A', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_logs', to='myapa.Contact')),
                ('reinstatement_end_time', models.DateTimeField(blank=True, null=True, verbose_name='reinstatement end time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('begin_time', models.DateTimeField(blank=True, null=True, verbose_name='begin time')),
                ('law_credits_required', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('ethics_credits_required', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('credits_required', models.DecimalField(decimal_places=2, default=32, max_digits=6)),
            ],
            options={
                'verbose_name': 'CM log',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='An identifier for the ending of the url - will be auto-generated based on the title for web pages.', null=True)),
                ('created_time', models.DateTimeField(editable=False)),
                ('updated_time', models.DateTimeField(editable=False)),
                ('begin_time', models.DateTimeField(blank=True, null=True, verbose_name='begin time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('grace_end_time', models.DateTimeField(blank=True, null=True, verbose_name='grace period end time')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_period_created_by', to=settings.AUTH_USER_MODEL)),
                ('rollover_from', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollover_to', to='cm.Period')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_period_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='log',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.Period'),
        ),
        migrations.AddField(
            model_name='claim',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='cm.Log'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'CM Provider',
            },
            bases=('myapa.contact',),
        ),
        migrations.AddField(
            model_name='claim',
            name='submitted_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 9, 13, 20, 39, 15, 578878, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProviderRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('CM_PER_CREDIT', 'Per-Credit'), ('CM_UNLIMITED_1', 'Annual Unlimited - Government and University Rate : $1,995 + $95 registration fee'), ('CM_UNLIMITED_INHOUSE', 'In House Annual Unlimited (for employee training only) : $475 + $95 registration fee'), ('CM_UNLIMITED_NONPROFIT_1', 'Annual Unlimited (nonprofit, less than $500,000) : $945 + $95 registration fee'), ('CM_UNLIMITED_NONPROFIT_2', 'Annual Unlimited (nonprofit, $500,000 to $5M) : $1,995 + $95 registration fee'), ('CM_UNLIMITED_NONPROFIT_3', 'Annual Unlimited (nonprofit, $5M to 15M) : $2,995 + $95 registration fee'), ('CM_UNLIMITED_NONPROFIT_4', 'Annual Unlimited (nonprofit, over $15M) : $5,145 + $95 registration fee'), ('CM_UNLIMITED_PARTNER', 'Unlimited registration through partner organization : $95'), ('CM_UNLIMITED_SMALL', 'For-Profit and Not-for-Profit Providers with gross revenue < $500K : $1,254'), ('CM_UNLIMITED_MEDIUM', 'Universities and  Governments - For-Profit and Not-for-Profit Providers with gross revenue $500K−$5M : $2,461 '), ('CM_UNLIMITED_LARGE', 'For-Profit and Not-for-Profit Providers with gross revenue $5M−$15M : $3,611 '), ('CM_UNLIMITED_LARGEST', 'For-Profit and Not-for-Profit Providers with gross revenue > $15M : $6,084 ')], default='CM_PER_CREDIT', max_length=50)),
                ('year', models.IntegerField(default=None)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='myapa.Contact')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_registration', to='store.Purchase')),
                ('shared_from_partner_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_to_partner_registration', to='cm.ProviderRegistration')),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='N', max_length=50)),
                ('is_unlimited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CMOrder',
            fields=[
            ],
            options={
                'verbose_name': 'CM Order',
                'proxy': True,
            },
            bases=('store.order',),
        ),
    ]
