# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_auto_20170921_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='review_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='review_status',
            field=models.CharField(blank=True, choices=[('DUE', 'Due for Review'), ('REVIEWING', 'Under Review'), ('COMPLETE', 'Review Complete')], default=None, max_length=50, null=True),
        ),
    ]
