# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-05 22:01
from __future__ import unicode_literals

import cm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0003_auto_20171002_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='objectives_example_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='supporting_upload_1',
            field=models.FileField(blank=True, null=True, upload_to=cm.models.supporting_document_file_path),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='supporting_upload_2',
            field=models.FileField(blank=True, null=True, upload_to=cm.models.supporting_document_file_path),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='supporting_upload_3',
            field=models.FileField(blank=True, null=True, upload_to=cm.models.supporting_document_file_path),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='review_status',
            field=models.CharField(blank=True, choices=[('DUE', 'Due for Review'), ('REVIEWING', 'Under Review'), ('COMPLETE', 'Review Complete'), ('LOCKED', 'Coaching')], default=None, max_length=50, null=True),
        ),
    ]
