# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-19 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_auto_20171005_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='provider_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes to Provider'),
        ),
    ]
