# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0005_providerapplication_provider_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='intended_registration_type',
        ),
    ]
