# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-29 21:23
from __future__ import unicode_literals

import cm.models.providers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0006_remove_providerapplication_intended_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], db_index=True, default='A', max_length=5, verbose_name='visibility status'),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='supporting_upload_1',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=cm.models.providers.supporting_document_file_path),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='supporting_upload_2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=cm.models.providers.supporting_document_file_path),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='supporting_upload_3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=cm.models.providers.supporting_document_file_path),
        ),
    ]
