# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-15 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0007_auto_20190729_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='author_type',
            field=models.CharField(blank=True, choices=[('PLANNING_ARTICLE', 'Planning-related Article'), ('PLANNING_JOURNAL_ARTICLE', 'Planning-related Journal Article'), ('PLANNING_BOOK', 'Planning-related Non-fiction Book')], max_length=50, null=True),
        ),
    ]
