# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-24 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0009_auto_20191217_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_claim', to='cm.CMComment'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cm_claims', to='myapa.Contact'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_claims', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='cm.Log'),
        ),
        migrations.AlterField(
            model_name='log',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cm_logs', to='myapa.Contact'),
        ),
        migrations.AlterField(
            model_name='log',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cm.Period'),
        ),
        migrations.AlterField(
            model_name='period',
            name='rollover_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollover_to', to='cm.Period'),
        ),
        migrations.AlterField(
            model_name='providerregistration',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_registration', to='store.Purchase'),
        ),
        migrations.AlterField(
            model_name='providerregistration',
            name='shared_from_partner_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_to_partner_registration', to='cm.ProviderRegistration'),
        ),
    ]
