# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-25 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0010_auto_20200324_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cm_period_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='period',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cm_period_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
