# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-24 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0011_auto_20200324_2217'),
        ('cm', '0010_auto_20200511_1634'),
    ]

    operations = [
    ]
