# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-12-02 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0012_merge_20200624_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='equity_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='targeted_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='targeted_credits_topic',
            field=models.CharField(blank=True, choices=[('SUSTAINABILITY_AND_RESILIENCE', 'Sustainability & Resilience')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='equity_credits_required',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='log',
            name='targeted_credits_required',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='log',
            name='targeted_credits_topic',
            field=models.CharField(blank=True, choices=[('SUSTAINABILITY_AND_RESILIENCE', 'Sustainability & Resilience')], max_length=100, null=True),
        ),
    ]
