# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-12-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0013_auto_20201202_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='equity_credits_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='targeted_credits_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
