# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20180622_1025'),
        ('content', '0016_auto_20180622_1025'),
        ('knowledgebase', '0003_auto_20180327_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSuggestion',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Resource Suggestions',
                'indexes': [],
                'verbose_name': 'Resource Suggestion',
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='ResourceSuggestionReview',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Resource Suggestions Reviews',
                'indexes': [],
                'verbose_name': 'Resource Suggestions Review',
            },
            bases=('submissions.review',),
        ),
        migrations.CreateModel(
            name='ResourceSuggestionReviewRole',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('submissions.reviewrole',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Story Submissions',
                'indexes': [],
                'verbose_name': 'Story Submission',
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='StoryReview',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Story Submissions Reviews',
                'indexes': [],
                'verbose_name': 'Story Submissions Review',
            },
            bases=('submissions.review',),
        ),
        migrations.CreateModel(
            name='StoryReviewRole',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('submissions.reviewrole',),
        ),
    ]
