# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20180627_1519'),
        ('knowledgebase', '0004_resourcesuggestion_resourcesuggestionreview_resourcesuggestionreviewrole_story_storyreview_storyrevi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceSuggestionReviewRole',
        ),
        migrations.DeleteModel(
            name='StoryReviewRole',
        ),
        migrations.CreateModel(
            name='SuggestionReviewRole',
            fields=[
            ],
            options={
                'verbose_name': 'Story/Suggestion Review Role',
                'verbose_name_plural': 'Story/Suggestion Review Roles',
                'proxy': True,
                'indexes': [],
            },
            bases=('submissions.reviewrole',),
        ),
    ]
