# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_squashed_0010_auto_20161018_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content_type',
            field=models.CharField(choices=[('PAGE', 'Web page'), ('EVENT', 'Events & training'), ('RFP', 'RFP/RFQ'), ('KNOWLEDGEBASE', 'Planning knowledgebase entry'), ('KNOWLEDGEBASE_COLLECTION', 'Planning knowledgebase collection'), ('AWARD', 'Award nomination'), ('RESEARCH_INQUIRY', 'Research inquiry'), ('IMAGE', 'Image library image'), ('MEDIA', 'Media asset'), ('PRODUCT', 'Other product'), ('PUBLICATION', 'Publication (article or resource)'), ('BLOG', 'Blog post'), ('EXAM', 'Exam application submission'), ('JOB', 'Job ad')], default='PAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='period',
            name='content_type',
            field=models.CharField(choices=[('PAGE', 'Web page'), ('EVENT', 'Events & training'), ('RFP', 'RFP/RFQ'), ('KNOWLEDGEBASE', 'Planning knowledgebase entry'), ('KNOWLEDGEBASE_COLLECTION', 'Planning knowledgebase collection'), ('AWARD', 'Award nomination'), ('RESEARCH_INQUIRY', 'Research inquiry'), ('IMAGE', 'Image library image'), ('MEDIA', 'Media asset'), ('PRODUCT', 'Other product'), ('PUBLICATION', 'Publication (article or resource)'), ('BLOG', 'Blog post'), ('EXAM', 'Exam application submission'), ('JOB', 'Job ad')], default='AWARDS', max_length=50),
        ),
    ]
