# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20180622_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.CharField(choices=[('REVIEW_RECEIVED', 'Review Recieved'), ('REVIEW_UNDERWAY', 'Review Underway'), ('REVIEW_COMPLETE_ADDED', 'Review Completed: ADDED'), ('REVIEW_COMPLETE_DUPLICATIVE', 'Review Completed: DUPLICATIVE'), ('REVIEW_COMPLETE_OFF_TOPIC', 'Review Completed: OFF-TOPIC')], default='REVIEW_RECEIVED', max_length=50),
        ),
    ]
