# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20180627_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.CharField(choices=[('REVIEW_RECEIVED', 'Review Received'), ('REVIEW_UNDERWAY', 'Review Underway'), ('REVIEW_COMPLETE_ADDED', 'Review Completed: ADDED'), ('REVIEW_COMPLETE_DUPLICATIVE', 'Review Completed: DUPLICATIVE'), ('REVIEW_COMPLETE_OFF_TOPIC', 'Review Completed: OFF-TOPIC')], default='REVIEW_RECEIVED', max_length=50),
        ),
    ]
