# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0001_squashed_0052_auto_20160331_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffContact',
            fields=[
            ],
            options={
                'verbose_name': 'APA staff / admin user',
                'proxy': True,
            },
            bases=('myapa.individualcontact',),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='olduser_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='staff_teams',
            field=models.CharField(blank=True, help_text='Department/team names for APA staff for granting django admin access. \n        Staff may belong to multiple teams if they perform cross-departmental work that requires\n        access to specific apps or pages. Enter possibly values in CAPS, \n        separated by commas. Possible values: AICP, MARKETING, MEMBERSHIP, EDUCATION, CAREERS,\n        PUBLICATIONS, RESEARCH, COMMUNICATIONS, CONFERENCE, LEADERSHIP, EVENTS-EDITOR, KNOWLEDGEBASE-EDITOR.\n        ', max_length=200, null=True),
        ),
    ]
