# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0002_auto_20170127_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='statement',
            field=models.TextField(blank=True, help_text='FAICP induction statement', null=True),
        ),
    ]
