# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0003_individualprofile_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='myapa.Contact')),
            ],
        ),
    ]
