# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0004_contactcommittee'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcommittee',
            name='position_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactcommittee',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
