# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0005_auto_20170427_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaldegree',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationaldegree',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationaldegree',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
