# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0010_educationaldegree_seqn'),
        ('myapa', '0010_auto_20170621_1441'),
    ]

    operations = [
    ]
