# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0011_merge_20170705_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cell Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Home Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Work Phone'),
        ),
    ]
