# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0012_auto_20170720_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaldegree',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
