# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0013_educationaldegree_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
