# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0014_contact_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrole',
            name='role_type',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('SPEAKER', 'Speaker'), ('ORGANIZER', 'Organizer / Coordinator'), ('PROPOSER', 'Proposer / Nominator'), ('PUBLISHER', 'Publisher'), ('PROVIDER', 'Provider'), ('PHOTOGRAPHER', 'Photographer'), ('ORGANIZER&SPEAKER', 'Organizer and Speaker'), ('MOBILEWORKSHOPGUIDE', 'Mobile Workshop Guide')], max_length=50),
        ),
    ]
