# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0015_auto_20171208_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcommittee',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ecp_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instructor_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='member_title',
        ),
        migrations.DeleteModel(
            name='ContactCommittee',
        ),
    ]
