# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0016_auto_20180327_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='speaker_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
