# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-27 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0021_auto_20181116_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrole',
            name='role_type',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('SPEAKER', 'Speaker'), ('ORGANIZER', 'Organizer / Coordinator'), ('PROPOSER', 'Proposer / Nominator'), ('PUBLISHER', 'Publisher'), ('PROVIDER', 'Provider'), ('PHOTOGRAPHER', 'Photographer'), ('ORGANIZER&SPEAKER', 'Organizer and Speaker'), ('MOBILEWORKSHOPGUIDE', 'Mobile Workshop Guide'), ('MODERATOR', 'Moderator'), ('ORGANIZER&MODERATOR', 'Session Organizer and Moderator'), ('LEADPOSTERPRESENTER', 'Lead Poster Presenter'), ('POSTERPRESENTER', 'Poster Presenter'), ('MOBILEWORKSHOPCOORDINATOR', 'Mobile Workshop Coordinator'), ('LEADMOBILEWORKSHOPCOORDINATOR', 'Lead Mobile Workshop Coordinator')], max_length=50),
        ),
    ]
