# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-21 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0023_auto_20181214_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrole',
            name='external_bio_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
