# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0023_auto_20181214_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
