# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-03 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0024_auto_20190403_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='employer_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
