# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-07 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0025_organizationprofile_employer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('PR001', 'Academia'), ('PR002', 'Nonprofit or Non-Governmental Organization'), ('PR005', 'Private - Consulting Firm'), ('PR006', 'Private - Law Firm'), ('PR003', 'Private - Other'), ('P001', 'Public Sector - Local Government'), ('P002', 'Public Sector - County Government'), ('P003', 'Public Sector - Regional Government'), ('P004', 'Public Sector - State Government'), ('P005', 'Public Sector - Federal Government'), ('P999', 'Public Sector - Other'), ('PR004', 'Regional Entity')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], db_index=True, default='A', max_length=5, verbose_name='visibility status'),
        ),
        migrations.AlterField(
            model_name='contactrole',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='contacttagtype',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], db_index=True, default='DRAFT', max_length=50),
        ),
    ]
