# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-10 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0026_auto_20190507_1354'),
        ('myapa', '0024_auto_20190521_1535'),
    ]

    operations = [
    ]
