# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0027_merge_20190610_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrole',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrole',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='share_profile',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('MEMBER', 'Visible only to other members')], default='MEMBER', help_text='If you choose “Private,” your profile is not included in the APA Member Directory.\n                Only you may view your profile, even if someone else knows your profile’s URL.\n                <br/><br/>\n                If you choose “Visible only to other members,” your profile is included in the APA Member Directory,\n                which is accessible only to APA members. Any APA member may view your profile by searching the APA member\n                directory or by using your profile’s URL.\n                <br/><br/>\n                If you choose “Public,” your profile is included in the APA Member Directory.\n                Additionally, anyone who has your profile’s URL - APA member or not - may view your profile.', max_length=50),
        ),
    ]
