# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapa', '0030_auto_20200124_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='myapa.Organization', verbose_name='linked organization'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branchoffice', to='myapa.Organization', verbose_name='parent organization'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='staff_teams',
            field=models.TextField(blank=True, help_text='Department/team names for APA staff for granting django admin access.\n        Staff may belong to multiple teams if they perform cross-departmental work that requires\n        access to specific apps or pages. Enter values in CAPS,\n        separated by commas WITH NO SPACES. Possible values:\n        AICP,\n        CAREERS,\n        COMMUNICATIONS,\n        COMPONENT_ADMIN,\n        COMPONENT_BLACK,\n        COMPONENT_CITY,\n        COMPONENT_HOUSING,\n        COMPONENT_PRIVATE,\n        COMPONENT_TRANS,\n        COMPONENT_URBAN_DES,\n        COMPONENT_WOMEN,\n        CONFERENCE,\n        EDITOR,\n        EDUCATION,\n        EVENTS_EDITOR,\n        KNOWLEDGEBASE_EDITOR,\n        LEADERSHIP,\n        MARKETING,\n        MEMBERSHIP,\n        PUBLICATIONS,\n        RESEARCH,\n        STORE_ADMIN,\n        TEMP_STAFF\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='contactrole',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactrole', to='myapa.Contact'),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_degree', to='myapa.School'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_profile', to='uploads.ImageUpload'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.DocumentUpload'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.ImageUpload'),
        ),
    ]
