# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import publications.models


class Migration(migrations.Migration):

    # replaces = [('publications', '0001_squashed_0007_auto_20160401_1553'), ('publications', '0002_auto_20160601_2336'), ('publications', '0003_auto_20161018_1735')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('content', '0001_squashed_0012_auto_20161018_1735'),
        ('content', '0001_squashed_0064_auto_20160328_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFormatsRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='An identifier for the ending of the url - will be auto-generated based on the title for web pages.', null=True)),
                ('created_time', models.DateTimeField(editable=False)),
                ('updated_time', models.DateTimeField(editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_multipleformatsrelated_created_by', to=settings.AUTH_USER_MODEL)),
                ('related_content', models.ManyToManyField(related_name='multiple_formats', to='content.MasterContent')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_multipleformatsrelated_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'publications with multiple formats for sale',
                'verbose_name': 'publication with multiple formats for sale',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('table_of_contents', models.TextField(blank=True, null=True)),
                ('publication_format', models.CharField(choices=[('ONLINE', 'Online'), ('BOOK_PAPERBACK', 'Paperback'), ('BOOK_HARDCOVER', 'Hardcover'), ('DOWNLOAD_PDF', 'Adobe PDF'), ('DOWNLOAD_EPUB', 'EPUB'), ('DOWNLOAD_MOBI', 'MOBI'), ('CD', 'CD')], default='Paperback', max_length=50)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_download', models.FileField(blank=True, null=True, upload_to=publications.models.Publication.generate_file_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Specialty publication article',
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'e-book',
            },
            bases=('publications.book',),
        ),
        migrations.CreateModel(
            name='PlanningMagArticle',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Planning magazine article',
            },
            bases=('publications.article',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('publications.publication',),
        ),        
        # migrations.AlterField(
        #     model_name='publication',
        #     name='publication_format',
        #     field=models.CharField(choices=[('ONLINE', 'Online'), ('BOOK_PAPERBACK', 'Paperback'), ('BOOK_HARDCOVER', 'Hardcover'), ('DOWNLOAD_PDF', 'Adobe PDF'), ('DOWNLOAD_EPUB', 'EPUB'), ('DOWNLOAD_MOBI', 'MOBI'), ('CD', 'CD')], default='Paperback', max_length=50),
        # ),
    ]
