# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_squashed_0003_auto_20161018_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDocument',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('publications.publication',),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_format',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('BOOK_PAPERBACK', 'Paperback'), ('BOOK_HARDCOVER', 'Hardcover'), ('DOWNLOAD_PDF', 'Adobe PDF'), ('DOWNLOAD_EPUB', 'EPUB'), ('DOWNLOAD_MOBI', 'MOBI'), ('OTHER', 'Other format'), ('CD', 'CD')], default='Paperback', max_length=50),
        ),
    ]
