# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-02-23 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20210223_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author_bios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='date_text',
            field=models.TextField(blank=True, null=True, verbose_name='Editable publication date'),
        ),
        migrations.AddField(
            model_name='publication',
            name='sort_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sort date and time'),
        ),
    ]
