# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-03-29 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20210329_1303'),
        ('publications', '0004_auto_20210223_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningMagFeaturedContentTagType',
            fields=[
            ],
            options={
                'verbose_name': 'Article Featured Zone',
                'verbose_name_plural': 'Article Featured Zones',
                'proxy': True,
                'indexes': [],
            },
            bases=('content.contenttagtype',),
        ),
        migrations.CreateModel(
            name='PlanningMagSectionContentTagType',
            fields=[
            ],
            options={
                'verbose_name': 'Article Section',
                'verbose_name_plural': 'Article Sections',
                'proxy': True,
                'indexes': [],
            },
            bases=('content.contenttagtype',),
        ),
        migrations.CreateModel(
            name='PlanningMagSeriesContentTagType',
            fields=[
            ],
            options={
                'verbose_name': 'Article Series',
                'verbose_name_plural': 'Article Series',
                'proxy': True,
                'indexes': [],
            },
            bases=('content.contenttagtype',),
        ),
        migrations.CreateModel(
            name='PlanningMagSlugContentTagType',
            fields=[
            ],
            options={
                'verbose_name': 'Article Slug',
                'verbose_name_plural': 'Article Slugs',
                'proxy': True,
                'indexes': [],
            },
            bases=('content.contenttagtype',),
        ),
        migrations.CreateModel(
            name='PlanningMagSponsoredContentTagType',
            fields=[
            ],
            options={
                'verbose_name': 'Sponsored Article',
                'verbose_name_plural': 'Sponsored Articles',
                'proxy': True,
                'indexes': [],
            },
            bases=('content.contenttagtype',),
        ),
    ]
