# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0016_auto_20180710_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnCourse',
            fields=[
            ],
            options={
                'verbose_name': 'APA Learn Course',
                'indexes': [],
                'proxy': True,
            },
            bases=('events.event',),
        ),
    ]
