# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnCourseBundle',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name': 'APA Learn Course Bundle',
                'proxy': True,
            },
            bases=('learn.learncourse',),
        ),
    ]
