# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180726_1415'),
        ('store', '0010_auto_20180710_1638'),
        ('myapa', '0017_individualprofile_speaker_opt_out'),
        ('learn', '0002_learncoursebundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_code', models.CharField(blank=True, max_length=100, null=True)),
                ('redemption_date', models.DateTimeField(blank=True, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_group_licenses', to='store.Purchase')),
                ('redemption_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_group_licenses', to='myapa.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='LearnCourseEvaluation',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'APA Learn Course Eval/Completion',
                'indexes': [],
            },
            bases=('comments.extendedeventevaluation',),
        ),
    ]
