# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-14 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_grouplicense_learncourseevaluation_learnspeakerevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplicense',
            name='redemption_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learn_group_licenses', to='myapa.Contact'),
        ),
    ]
