# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_learncourseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learncourseinfo',
            name='activity_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_to_info', to='conference.NationalConferenceActivity'),
        ),
        migrations.AlterField(
            model_name='learncourseinfo',
            name='course_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_from_info', to='learn.LearnCourse', verbose_name='Related APA Learn Course'),
        ),
    ]
