# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-25 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20191217_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplicense',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learn_group_licenses', to='store.Purchase'),
        ),
    ]
