# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_squashed_0008_auto_20160328_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NationalConferenceAttendee',
        ),
    ]
