# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-25 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20200124_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='store.Purchase'),
        ),
    ]
