import django
django.setup()
from _data_tools.pas import *
change_pas_book_prices_groups()
print("DONE: change_pas_book_prices_groups()")
change_eip_document_prices_groups()
print("DONE: change_eip_document_prices_groups()")
copy_description_to_text()
print("DONE: copy_description_to_text()")
add_member_to_eip()
print("DONE: add_member_to_eip()")
add_member_to_memo()
print("DONE: add_member_to_memo()")
unpublish_you_asked()
print("DONE: unpublish_you_asked()")
add_member_pas_to_books()
print("DONE: add_member_pas_to_books()")
add_member_pas_to_eip_documents()
print("DONE: add_member_pas_to_eip_documents()")
add_member_to_memo_documents()
print("DONE: add_member_to_memo_documents()")
add_member_to_quicknotes()
print("DONE: add_member_to_quicknotes()")
