# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_submissions_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='template',
            field=models.CharField(blank=True, choices=[('pages/default.html', 'Default web page'), ('cm/newtheme/aicp-page-sidebar.html', 'AICP branded page with sidebar'), ('blog/post.html', 'Blog Post'), ('knowledgebase/collection.html', 'Knowledgebase collection template'), ('knowledgebase/resource.html', 'Knowledgebase resource template'), ('events/newtheme/eventmulti_details.html', 'Multipart event template'), ('events/newtheme/ondemand/course_details.html', 'On-demand template'), ('publications/planning_mag.html', 'Planning Magazine article'), ('newtheme/store/product/details.html', 'Product template'), ('pages/research.html', 'Research project'), ('pages/section_overview.html', 'Section overview page'), ('events/newtheme/event_details.html', 'Single event or activity template'), ('pages/landing.html', 'Topic landing page'), ('content/oldtheme/base-details.html', '[Interim conference design template]'), ('content/test_details.html', '[APA test template (for testing only)]'), ('content/landingpage_template.html', '[Old/interim design promo/landing page template]'), ('PAGE', '[Old/interim design template]')], max_length=50, null=True),
        ),
    ]
