# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170202_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='template',
            field=models.CharField(blank=True, choices=[('pages/newtheme/default.html', 'Default web page'), ('cm/newtheme/aicp-page-sidebar.html', 'AICP branded page with sidebar'), ('blog/newtheme/post.html', 'Blog Post'), ('knowledgebase/newtheme/collection.html', 'Knowledgebase collection template'), ('knowledgebase/newtheme/resource.html', 'Knowledgebase resource template'), ('events/newtheme/eventmulti-details.html', 'Multipart event template'), ('events/newtheme/ondemand/course-details.html', 'On-demand template'), ('publications/newtheme/planning-mag.html', 'Planning Magazine article'), ('store/newtheme/product/details.html', 'Product template'), ('pages/newtheme/research.html', 'Research project'), ('pages/newtheme/section-overview.html', 'Section overview page'), ('events/newtheme/event-details.html', 'Single event or activity template'), ('pages/newtheme/landing.html', 'Topic landing page'), ('PAGE', '[Old/interim design template]')], max_length=50, null=True),
        ),
    ]
