# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_squashed_0004_auto_20160105_2018'),
        ('content', '0008_auto_20170502_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='og_image_content', to='media.MediaImageMasterContent'),
        ),
        migrations.AddField(
            model_name='content',
            name='og_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='og_type',
            field=models.CharField(blank=True, choices=[('article', 'article'), ('book', 'book'), ('books.author', 'books.author'), ('books.book', 'books.book'), ('books.genre', 'books.genre'), ('business.business', 'business.business'), ('fitness.course', 'fitness.course'), ('game.achievement', 'game.achievement'), ('music.album', 'music.album'), ('music.playlist', 'music.playlist'), ('music.radio_station', 'music.radio_station'), ('music.song', 'music.song'), ('place', 'place'), ('product', 'product'), ('product.group', 'product.group'), ('product.item', 'product.item'), ('profile', 'profile'), ('restaurant.menu', 'restaurant.menu'), ('restaurant.menu_item', 'restaurant.menu_item'), ('restaurant.menu_section', 'restaurant.menu_section'), ('restaurant.restaurant', 'restaurant.restaurant'), ('video.episode', 'video.episode'), ('video.movie', 'video.movie'), ('video.other', 'video.other'), ('video.tv_show', 'video.tv_show')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='og_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
