# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20171031_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('PAGE', 'Web page'), ('EVENT', 'Events & training'), ('RFP', 'RFP/RFQ'), ('KNOWLEDGEBASE', 'Planning knowledgebase entry'), ('KNOWLEDGEBASE_COLLECTION', 'Planning knowledgebase collection'), ('AWARD', 'Award nomination'), ('RESEARCH_INQUIRY', 'Research inquiry'), ('IMAGE', 'Image library image'), ('MEDIA', 'Media asset'), ('PRODUCT', 'Other product'), ('PUBLICATION', 'Publication (article or resource)'), ('BLOG', 'Blog post'), ('EXAM', 'Exam application submission'), ('JOB', 'Job ad')], default='PAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('BOOK', 'Book'), ('EBOOK', 'E-Book'), ('ARTICLE', 'Article'), ('REPORT', 'Report'), ('PUBLICATION_DOCUMENT', 'Publication Document'), ('TOOLKIT', 'Toolkit'), ('E_LEARNING', 'E-Learning')], help_text='A subset of the APA format facet, used for publications.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='template',
            field=models.CharField(blank=True, choices=[('pages/newtheme/default.html', 'Default web page'), ('cm/newtheme/aicp-page-sidebar.html', 'AICP branded page with sidebar'), ('blog/newtheme/post.html', 'Blog Post'), ('store/newtheme/foundation/page-sidenav.html', 'Foundation branded page with sidebar'), ('knowledgebase/newtheme/collection.html', 'Knowledgebase collection template'), ('knowledgebase/newtheme/resource.html', 'Knowledgebase resource template'), ('events/newtheme/eventmulti-details.html', 'Multipart event template'), ('events/newtheme/ondemand/course-details.html', 'On-demand template'), ('publications/newtheme/planning-mag.html', 'Planning Magazine article'), ('store/newtheme/product/details.html', 'Product template'), ('pages/newtheme/research.html', 'Research project'), ('pages/newtheme/section-overview.html', 'Section overview page'), ('events/newtheme/event-details.html', 'Single event or activity template'), ('pages/newtheme/landing.html', 'Topic landing page'), ('pages/newtheme/full-width.html', 'Full Width (no side nav)'), ('newtheme/templates/conference/page-ads.html', 'Conference (Original Page Template)'), ('newtheme/templates/conference/page-widget.html', 'Conference Page WITH Sidebar AND WIDGET'), ('newtheme/templates/conference/page-sidebar.html', 'Conference Page WITH Sidebar (general)'), ('newtheme/templates/conference/page-nosidebar.html', 'Conference Page WITHOUT Sidebar'), ('events/newtheme/conference-details.html', 'Conference Activity Details'), ('conference/newtheme/home.html', 'Conference Home'), ('PAGE', '[Old/interim design template]')], max_length=50, null=True),
        ),
    ]
