# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20180131_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contentimage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='new_landing_page',
        ),
        migrations.RemoveField(
            model_name='section',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='section',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ContentTaxoUpload',
        ),
        migrations.RemoveField(
            model_name='content',
            name='section',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='section',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('PAGE', 'Web page'), ('EVENT', 'Events & training'), ('RFP', 'RFP/RFQ'), ('KNOWLEDGEBASE', 'Planning knowledgebase entry'), ('KNOWLEDGEBASE_COLLECTION', 'Planning knowledgebase collection'), ('AWARD', 'Award nomination'), ('RESEARCH_INQUIRY', 'Research inquiry'), ('IMAGE', 'Image library image'), ('MEDIA', 'Media asset'), ('PRODUCT', 'Other product'), ('PUBLICATION', 'Publication (article or resource)'), ('BLOG', 'Blog post'), ('EXAM', 'Exam application submission'), ('JOB', 'Job ad')], default='EVENT', max_length=50),
        ),
        migrations.DeleteModel(
            name='ContentImage',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
