# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-11 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20180710_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrelationship',
            name='relationship',
            field=models.CharField(choices=[('RELATED', 'Related'), ('KNOWLEDGEBASE_COLLECTION', 'Belongs to knowledgebase collection'), ('LEARN_COURSE', 'Learn course derived from conference activity')], max_length=50),
        ),
    ]
