# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20180817_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], db_index=True, default='A', max_length=5, verbose_name='visibility status'),
        ),
        migrations.AlterField(
            model_name='contentrelationship',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='contenttagtype',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], db_index=True, default='A', max_length=5, verbose_name='visibility status'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], db_index=True, default='A', max_length=5, verbose_name='visibility status'),
        ),
        migrations.AlterField(
            model_name='messagetext',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='messagetext',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], db_index=True, default='A', max_length=5, verbose_name='visibility status'),
        ),
        migrations.AlterField(
            model_name='serialpub',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], db_index=True, default='A', max_length=5, verbose_name='visibility status'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], db_index=True, default='A', max_length=5, verbose_name='visibility status'),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], db_index=True, default='A', max_length=5, verbose_name='visibility status'),
        ),
    ]
