# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-24 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_auto_20200324_1725'),
        ('content', '0027_auto_20200324_1742'),
    ]

    operations = [
    ]
