# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-03-15 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20210223_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='featured_image_caption',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('PAGE', 'Web page'), ('EVENT', 'Events & training'), ('RFP', 'RFP/RFQ'), ('KNOWLEDGEBASE', 'Planning knowledgebase entry'), ('KNOWLEDGEBASE_COLLECTION', 'Planning knowledgebase collection'), ('KNOWLEDGEBASE_STORY', 'Planning knowledgebase story'), ('KNOWLEDGEBASE_SUGGESTION', 'Planning knowledgebase resource suggestion'), ('AWARD', 'Award nomination'), ('RESEARCH_INQUIRY', 'Research inquiry'), ('IMAGE', 'Image library image'), ('MEDIA', 'Media asset'), ('PRODUCT', 'Other product'), ('PUBLICATION', 'Publication (article or resource)'), ('BLOG', 'Blog post'), ('EXAM', 'Exam application submission'), ('JOB', 'Job ad')], default='PAGE', max_length=50),
        ),
    ]
