# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-03-29 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20210315_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('PAGE', 'Web page'), ('EVENT', 'Events & training'), ('RFP', 'RFP/RFQ'), ('KNOWLEDGEBASE', 'Planning knowledgebase entry'), ('KNOWLEDGEBASE_COLLECTION', 'Planning knowledgebase collection'), ('KNOWLEDGEBASE_STORY', 'Planning knowledgebase story'), ('KNOWLEDGEBASE_SUGGESTION', 'Planning knowledgebase resource suggestion'), ('AWARD', 'Award nomination'), ('RESEARCH_INQUIRY', 'Research inquiry'), ('IMAGE', 'Image library image'), ('MEDIA', 'Media asset'), ('PRODUCT', 'Other product'), ('PUBLICATION', 'Publication (article or resource)'), ('BLOG', 'Blog post'), ('EXAM', 'Exam application submission'), ('JOB', 'Job ad')], default='EVENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='template',
            field=models.CharField(blank=True, choices=[('pages/newtheme/default.html', 'Default web page'), ('cm/newtheme/aicp-page-sidebar.html', 'AICP branded page with sidebar'), ('blog/newtheme/post.html', 'Blog Post'), ('store/newtheme/foundation/page-sidenav.html', 'Foundation branded page with sidebar'), ('knowledgebase/newtheme/collection.html', 'Knowledgebase collection template'), ('knowledgebase/newtheme/resource.html', 'Knowledgebase resource template'), ('knowledgebase/newtheme/story.html', 'Knowledgebase story template'), ('events/newtheme/eventmulti-details.html', 'Multipart event template'), ('events/newtheme/ondemand/course-details.html', 'On-demand template'), ('learn/newtheme/course-details.html', 'APA Learn course template'), ('publications/newtheme/planning-mag.html', 'Planning Magazine article (OLD)'), ('publications/newtheme/planning-mag-article.html', 'Planning Magazine article'), ('store/newtheme/product/details.html', 'Product template'), ('publications/newtheme/publication-document.html', 'Publication document template'), ('pages/newtheme/research.html', 'Research project'), ('pages/newtheme/section-overview.html', 'Section overview page'), ('events/newtheme/event-details.html', 'Single event or activity template'), ('pages/newtheme/landing.html', 'Topic landing page'), ('pages/newtheme/full-width.html', 'Full Width (no side nav)'), ('newtheme/templates/conference/page-ads.html', 'Conference (Original Page Template)'), ('newtheme/templates/conference/page-widget.html', 'Conference Page WITH Sidebar AND WIDGET'), ('newtheme/templates/conference/page-sidebar.html', 'Conference Page WITH Sidebar (general)'), ('newtheme/templates/conference/page-nosidebar.html', 'Conference Page WITHOUT Sidebar'), ('events/newtheme/conference-details.html', 'Conference Activity Details'), ('events/newtheme/conference-details-embed.html', 'Conference Activity Details WITH Embed'), ('conference/newtheme/home.html', 'Conference Home'), ('pages/micro/home.html', 'Micro home page'), ('pages/micro/default.html', 'Micro default page'), ('pages/micro/section-overview.html', 'Micro section overview page'), ('pages/micro/landing.html', 'Micro topic landing page'), ('pages/micro/home/default.html', 'Home default page'), ('pages/micro/home/section-overview.html', 'Home section overview page'), ('pages/micro/home/landing.html', 'Home topic landing page'), ('pages/newtheme/media.html', 'Media Page'), ('pages/newtheme/jotform.html', 'JotForm Page')], max_length=50, null=True),
        ),
    ]
