# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('org_code', models.CharField(db_column='ORG_CODE', max_length=5)),
                ('member_type', models.CharField(db_column='MEMBER_TYPE', max_length=5)),
                ('category', models.CharField(db_column='CATEGORY', max_length=5)),
                ('status', models.CharField(db_column='STATUS', max_length=5)),
                ('major_key', models.CharField(db_column='MAJOR_KEY', max_length=15)),
                ('co_id', models.CharField(db_column='CO_ID', max_length=10)),
                ('last_first', models.CharField(db_column='LAST_FIRST', max_length=70)),
                ('company_sort', models.CharField(db_column='COMPANY_SORT', max_length=30)),
                ('bt_id', models.CharField(db_column='BT_ID', max_length=10)),
                ('dup_match_key', models.CharField(db_column='DUP_MATCH_KEY', max_length=20)),
                ('full_name', models.CharField(db_column='FULL_NAME', max_length=70)),
                ('title', models.CharField(db_column='TITLE', max_length=80)),
                ('company', models.CharField(db_column='COMPANY', max_length=80)),
                ('full_address', models.CharField(db_column='FULL_ADDRESS', max_length=255)),
                ('prefix', models.CharField(db_column='PREFIX', max_length=25)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=20)),
                ('middle_name', models.CharField(db_column='MIDDLE_NAME', max_length=20)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=30)),
                ('suffix', models.CharField(db_column='SUFFIX', max_length=10)),
                ('designation', models.CharField(db_column='DESIGNATION', max_length=20)),
                ('informal', models.CharField(db_column='INFORMAL', max_length=20)),
                ('work_phone', models.CharField(db_column='WORK_PHONE', max_length=25)),
                ('home_phone', models.CharField(db_column='HOME_PHONE', max_length=25)),
                ('fax', models.CharField(db_column='FAX', max_length=25)),
                ('toll_free', models.CharField(db_column='TOLL_FREE', max_length=25)),
                ('city', models.CharField(db_column='CITY', max_length=40)),
                ('state_province', models.CharField(db_column='STATE_PROVINCE', max_length=15)),
                ('zip', models.CharField(db_column='ZIP', max_length=10)),
                ('country', models.CharField(db_column='COUNTRY', max_length=25)),
                ('mail_code', models.CharField(db_column='MAIL_CODE', max_length=5)),
                ('crrt', models.CharField(db_column='CRRT', max_length=40)),
                ('bar_code', models.CharField(db_column='BAR_CODE', max_length=14)),
                ('county', models.CharField(db_column='COUNTY', max_length=30)),
                ('mail_address_num', models.IntegerField(db_column='MAIL_ADDRESS_NUM')),
                ('bill_address_num', models.IntegerField(db_column='BILL_ADDRESS_NUM')),
                ('gender', models.CharField(db_column='GENDER', max_length=1)),
                ('birth_date', models.DateTimeField(blank=True, db_column='BIRTH_DATE', null=True)),
                ('us_congress', models.CharField(db_column='US_CONGRESS', max_length=20)),
                ('state_senate', models.CharField(db_column='STATE_SENATE', max_length=20)),
                ('state_house', models.CharField(db_column='STATE_HOUSE', max_length=20)),
                ('sic_code', models.CharField(db_column='SIC_CODE', max_length=10)),
                ('chapter', models.CharField(db_column='CHAPTER', max_length=15)),
                ('functional_title', models.CharField(db_column='FUNCTIONAL_TITLE', max_length=50)),
                ('contact_rank', models.IntegerField(db_column='CONTACT_RANK')),
                ('member_record', models.BooleanField(db_column='MEMBER_RECORD')),
                ('company_record', models.BooleanField(db_column='COMPANY_RECORD')),
                ('join_date', models.DateTimeField(blank=True, db_column='JOIN_DATE', null=True)),
                ('source_code', models.CharField(db_column='SOURCE_CODE', max_length=40)),
                ('paid_thru', models.DateTimeField(blank=True, db_column='PAID_THRU', null=True)),
                ('member_status', models.CharField(db_column='MEMBER_STATUS', max_length=5)),
                ('member_status_date', models.DateTimeField(blank=True, db_column='MEMBER_STATUS_DATE', null=True)),
                ('previous_mt', models.CharField(db_column='PREVIOUS_MT', max_length=5)),
                ('mt_change_date', models.DateTimeField(blank=True, db_column='MT_CHANGE_DATE', null=True)),
                ('co_member_type', models.CharField(db_column='CO_MEMBER_TYPE', max_length=5)),
                ('exclude_mail', models.BooleanField(db_column='EXCLUDE_MAIL')),
                ('exclude_directory', models.BooleanField(db_column='EXCLUDE_DIRECTORY')),
                ('date_added', models.DateTimeField(blank=True, db_column='DATE_ADDED', null=True)),
                ('last_updated', models.DateTimeField(blank=True, db_column='LAST_UPDATED', null=True)),
                ('updated_by', models.CharField(db_column='UPDATED_BY', max_length=60)),
                ('intent_to_edit', models.CharField(db_column='INTENT_TO_EDIT', max_length=80)),
                ('address_num_1', models.IntegerField(db_column='ADDRESS_NUM_1')),
                ('address_num_2', models.IntegerField(db_column='ADDRESS_NUM_2')),
                ('address_num_3', models.IntegerField(db_column='ADDRESS_NUM_3')),
                ('email', models.CharField(db_column='EMAIL', max_length=100)),
                ('website', models.CharField(db_column='WEBSITE', max_length=255)),
                ('ship_address_num', models.IntegerField(db_column='SHIP_ADDRESS_NUM')),
                ('display_currency', models.CharField(db_column='DISPLAY_CURRENCY', max_length=3)),
                ('mobile_phone', models.CharField(db_column='MOBILE_PHONE', max_length=25)),
            ],
            options={
                'managed': False,
                'db_table': 'Name',
            },
        ),
    ]
