# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imis', '0002_activity_customdegree_customschoolaccredited_inddemographics_nameaddress_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocacy',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('congressional_district', models.CharField(db_column='Congressional_District', max_length=5)),
                ('st_house', models.CharField(db_column='St_House', max_length=5)),
                ('st_senate', models.CharField(db_column='St_Senate', max_length=5)),
                ('state_chair', models.BooleanField(db_column='State_Chair')),
                ('district_captain', models.BooleanField(db_column='District_Captain')),
                ('transportation', models.BooleanField(db_column='Transportation')),
                ('community_development', models.BooleanField(db_column='Community_Development')),
                ('federal_data', models.BooleanField(db_column='Federal_Data')),
                ('water', models.BooleanField(db_column='Water')),
                ('other', models.CharField(db_column='Other', max_length=255)),
                ('grassrootsmember', models.BooleanField(db_column='GrassRootsMember')),
                ('join_date', models.DateTimeField(blank=True, db_column='Join_Date', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Advocacy',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('counter_name', models.CharField(db_column='COUNTER_NAME', max_length=30, primary_key=True, serialize=False)),
                ('last_value', models.IntegerField(db_column='LAST_VALUE')),
                ('last_updated', models.DateTimeField(blank=True, db_column='LAST_UPDATED', null=True)),
                ('updated_by', models.CharField(db_column='UPDATED_BY', max_length=255)),
                ('pagepad1', models.CharField(db_column='PAGEPAD1', max_length=255)),
                ('pagepad2', models.CharField(db_column='PAGEPAD2', max_length=255)),
                ('pagepad3', models.CharField(db_column='PAGEPAD3', max_length=255)),
                ('pagepad4', models.CharField(db_column='PAGEPAD4', max_length=255)),
                ('has_checksum', models.BooleanField(db_column='HAS_CHECKSUM')),
            ],
            options={
                'managed': False,
                'db_table': 'Counter',
            },
        ),
    ]
