# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imis', '0003_advocacy_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingDemographics',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('job_mart_bulk', models.BooleanField(db_column='JOB_MART_BULK')),
                ('job_mart_address', models.CharField(db_column='JOB_MART_ADDRESS', max_length=20)),
                ('excl_all_sub_promos', models.BooleanField(db_column='EXCL_ALL_SUB_PROMOS')),
                ('excl_email', models.BooleanField(db_column='EXCL_EMAIL')),
                ('excl_affinity', models.BooleanField(db_column='EXCL_AFFINITY')),
                ('excl_bookstore', models.BooleanField(db_column='EXCL_BOOKSTORE')),
                ('excl_conference', models.BooleanField(db_column='EXCL_CONFERENCE')),
                ('excl_apamarketing', models.BooleanField(db_column='EXCL_APAMARKETING')),
                ('excl_mail_list', models.BooleanField(db_column='EXCL_MAIL_LIST')),
                ('excl_website', models.BooleanField(db_column='EXCL_WEBSITE')),
                ('excl_tuesdays', models.BooleanField(db_column='EXCL_TUESDAYS')),
                ('excl_interact', models.BooleanField(db_column='EXCL_INTERACT')),
                ('excl_china', models.BooleanField(db_column='EXCL_CHINA')),
                ('excl_survey', models.BooleanField(db_column='EXCL_SURVEY')),
                ('leadership_address', models.CharField(db_column='LEADERSHIP_ADDRESS', max_length=20)),
                ('roster_address', models.CharField(db_column='ROSTER_ADDRESS', max_length=20)),
                ('speaker_address', models.CharField(db_column='SPEAKER_ADDRESS', max_length=20)),
                ('excl_all', models.BooleanField(db_column='EXCL_ALL')),
                ('job_mart_invoice', models.CharField(db_column='JOB_MART_INVOICE', max_length=20)),
                ('excl_natlconf', models.BooleanField(db_column='EXCL_NATLCONF')),
                ('excl_otherconf', models.BooleanField(db_column='EXCL_OTHERCONF')),
                ('excl_planning', models.BooleanField(db_column='EXCL_PLANNING')),
                ('excl_japa', models.BooleanField(db_column='EXCL_JAPA')),
                ('excl_zp', models.BooleanField(db_column='EXCL_ZP')),
                ('excl_pel', models.BooleanField(db_column='EXCL_PEL')),
                ('excl_pas', models.BooleanField(db_column='EXCL_PAS')),
                ('excl_commissioner', models.BooleanField(db_column='EXCL_COMMISSIONER')),
                ('excl_apaadvocate', models.BooleanField(db_column='EXCL_APAADVOCATE')),
                ('excl_insurance', models.BooleanField(db_column='EXCL_INSURANCE')),
                ('excl_japanews', models.BooleanField(db_column='EXCL_JAPANEWS')),
                ('excl_planning_print', models.BooleanField(db_column='EXCL_PLANNING_PRINT')),
                ('time_stamp', models.TextField(blank=True, db_column='TIME_STAMP', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Mailing_Demographics',
            },
        ),
        migrations.CreateModel(
            name='RaceOrigin',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('race', models.CharField(db_column='RACE', max_length=60)),
                ('origin', models.CharField(db_column='ORIGIN', max_length=60)),
                ('span_hisp_latino', models.CharField(db_column='SPAN_HISP_LATINO', max_length=60)),
                ('ai_an', models.CharField(db_column='AI_AN', max_length=60)),
                ('asian_pacific', models.CharField(db_column='ASIAN_PACIFIC', max_length=60)),
                ('other', models.CharField(db_column='OTHER', max_length=60)),
                ('ethnicity_verifydate', models.DateTimeField(blank=True, db_column='ETHNICITY_VERIFYDATE', null=True)),
                ('origin_verifydate', models.DateTimeField(blank=True, db_column='ORIGIN_VERIFYDATE', null=True)),
                ('ethnicity_noanswer', models.BooleanField(db_column='ETHNICITY_NOANSWER')),
                ('origin_noanswer', models.BooleanField(db_column='ORIGIN_NOANSWER')),
                ('time_stamp', models.TextField(blank=True, db_column='TIME_STAMP', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Race_Origin',
            },
        ),
    ]
