# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-28 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imis', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoresDemographics',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10)),
                ('pass_field', models.BooleanField(db_column='PASS')),
                ('fail', models.BooleanField(db_column='FAIL')),
                ('exams_remaining', models.FloatField(blank=True, db_column='EXAMS_REMAINING', null=True)),
                ('scaled_score', models.FloatField(blank=True, db_column='SCALED_SCORE', null=True)),
                ('raw_score', models.FloatField(blank=True, db_column='RAW_SCORE', null=True)),
                ('exam_date', models.DateTimeField(blank=True, db_column='EXAM_DATE', null=True)),
                ('score_1', models.FloatField(blank=True, db_column='SCORE_1', null=True)),
                ('score_2', models.FloatField(blank=True, db_column='SCORE_2', null=True)),
                ('score_3', models.FloatField(blank=True, db_column='SCORE_3', null=True)),
                ('score_4', models.FloatField(blank=True, db_column='SCORE_4', null=True)),
                ('score_5', models.FloatField(blank=True, db_column='SCORE_5', null=True)),
                ('score_6', models.FloatField(blank=True, db_column='SCORE_6', null=True)),
                ('score_7', models.FloatField(blank=True, db_column='SCORE_7', default=0, null=True)),
                ('score_8', models.FloatField(blank=True, db_column='SCORE_8', default=0, null=True)),
                ('testform_code', models.FloatField(blank=True, db_column='TESTFORM_CODE', null=True)),
                ('auto_counter', models.AutoField(db_column='AUTO_COUNTER', primary_key=True, serialize=False)),
                ('time_entered', models.DateTimeField(blank=True, db_column='TIME_ENTERED', null=True)),
                ('exam_code', models.CharField(blank=True, db_column='EXAM_CODE', max_length=15, null=True)),
                ('test_center', models.CharField(blank=True, db_column='TEST_CENTER', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=200, null=True)),
            ],
            options={
                'db_table': 'SCORES_Demographics',
                'managed': False,
            },
        ),
    ]
