# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-07 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imis', '0006_scoresdemographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC18_Speakers_Temp',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('address_1', models.CharField(db_column='ADDRESS_1', max_length=40)),
                ('address_2', models.CharField(db_column='ADDRESS_2', max_length=40)),
                ('city', models.CharField(db_column='CITY', max_length=40)),
                ('state_province', models.CharField(db_column='STATE_PROVINCE', max_length=15)),
                ('zip', models.CharField(db_column='ZIP', max_length=10)),
                ('country', models.CharField(db_column='COUNTRY', max_length=25)),
                ('fax', models.CharField(db_column='FAX', max_length=25)),
                ('email', models.CharField(db_column='EMAIL', max_length=100)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=20)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=30)),
                ('work_phone', models.CharField(db_column='WORK_PHONE', max_length=25)),
                ('cell_phone', models.CharField(db_column='CELL_PHONE', max_length=25)),
                ('pw', models.CharField(db_column='PW', max_length=50)),
            ],
            options={
                'db_table': '_NPC_2018_Speaker_Upload',
                'managed': False,
            },
        ),
    ]
