# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imis', '0009_meetmaster_productfunction_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_column='PRODUCT_CODE', max_length=31)),
                ('quantity_on_hand', models.DecimalField(db_column='QUANTITY_ON_HAND', decimal_places=4, max_digits=15)),
                ('quantity_reserved', models.DecimalField(db_column='QUANTITY_RESERVED', decimal_places=4, max_digits=15)),
                ('quantity_committed', models.DecimalField(db_column='QUANTITY_COMMITTED', decimal_places=4, max_digits=15)),
                ('quantity_available', models.DecimalField(db_column='QUANTITY_AVAILABLE', decimal_places=4, max_digits=15)),
                ('quantity_backordered', models.DecimalField(db_column='QUANTITY_BACKORDERED', decimal_places=4, max_digits=15)),
                ('quantity_on_order', models.DecimalField(db_column='QUANTITY_ON_ORDER', decimal_places=4, max_digits=15)),
                ('expected_arrival_date', models.DateTimeField(blank=True, db_column='EXPECTED_ARRIVAL_DATE', null=True)),
                ('ltd_orders', models.IntegerField(db_column='LTD_ORDERS')),
                ('ltd_quantity', models.DecimalField(db_column='LTD_QUANTITY', decimal_places=4, max_digits=15)),
                ('ltd_canceled_quantity', models.DecimalField(db_column='LTD_CANCELED_QUANTITY', decimal_places=4, max_digits=15)),
                ('ltd_income', models.DecimalField(db_column='LTD_INCOME', decimal_places=2, max_digits=15)),
                ('ltd_cost', models.DecimalField(db_column='LTD_COST', decimal_places=2, max_digits=15)),
                ('standard_cost', models.DecimalField(db_column='STANDARD_COST', decimal_places=2, max_digits=15)),
                ('latest_cost', models.DecimalField(db_column='LATEST_COST', decimal_places=2, max_digits=15)),
                ('average_cost', models.DecimalField(db_column='AVERAGE_COST', decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(db_column='TOTAL_COST', decimal_places=2, max_digits=15)),
                ('last_order_date', models.DateTimeField(blank=True, db_column='LAST_ORDER_DATE', null=True)),
                ('first_order_date', models.DateTimeField(blank=True, db_column='FIRST_ORDER_DATE', null=True)),
                ('last_received_date', models.DateTimeField(blank=True, db_column='LAST_RECEIVED_DATE', null=True)),
                ('minimum_order_point', models.IntegerField(db_column='MINIMUM_ORDER_POINT')),
                ('minimum_order_quantity', models.IntegerField(db_column='MINIMUM_ORDER_QUANTITY')),
                ('location', models.CharField(db_column='LOCATION', max_length=10)),
                ('bin', models.CharField(db_column='BIN', max_length=10)),
                ('income_account', models.CharField(db_column='INCOME_ACCOUNT', max_length=50)),
                ('inventory_account', models.CharField(db_column='INVENTORY_ACCOUNT', max_length=50)),
                ('cog_account', models.CharField(db_column='COG_ACCOUNT', max_length=50)),
                ('adjustment_account', models.CharField(db_column='ADJUSTMENT_ACCOUNT', max_length=50)),
            ],
            options={
                'db_table': 'Product_Inventory',
                'managed': False,
            },
        ),
    ]
