# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-05 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imis', '0012_npc19_speakers_temp'),
        ('imis', '0009_npc19_speakers_temp'),
    ]

    operations = [
    ]
