# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imis', '0013_merge_20181205_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_column='PRODUCT_CODE', max_length=31)),
                ('resource_type', models.CharField(db_column='RESOURCE_TYPE', default='', max_length=10)),
                ('res_group', models.CharField(db_column='RES_GROUP', default='', max_length=10)),
                ('code', models.CharField(db_column='CODE', default='', max_length=10)),
                ('line_no', models.IntegerField(db_column='LINE_NO', default=0)),
                ('fld1_qty', models.DecimalField(db_column='FLD1_QTY', decimal_places=4, default=0, max_digits=15)),
                ('fld1_time', models.DateTimeField(blank=True, db_column='FLD1_TIME', null=True)),
                ('fld1_check', models.BooleanField(db_column='FLD1_CHECK', default=0)),
                ('fld1_id', models.CharField(db_column='FLD1_ID', default='', max_length=10)),
                ('note', models.TextField(blank=True, db_column='NOTE', null=True)),
                ('time_stamp', models.TextField(blank=True, db_column='TIME_STAMP', null=True)),
            ],
            options={
                'db_table': 'Meet_Resources',
                'managed': False,
            },
        ),
    ]
