# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_squashed_0003_auto_20150806_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
