# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploads.models
import uuid


class Migration(migrations.Migration):

    # replaces = [('uploads', '0001_squashed_0012_auto_20160212_2132'), ('uploads', '0002_auto_20160518_2252'), ('uploads', '0003_auto_20161018_1735')]

    initial = True

    dependencies = [
        # ('content', '0001_squashed_0012_auto_20161018_1735'),
        ('content', '0001_squashed_0064_auto_20160328_1819'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=10, verbose_name='Extension')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='UploadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='An identifier for the ending of the url - will be auto-generated based on the title for web pages.', null=True)),
                ('created_time', models.DateTimeField(editable=False)),
                ('updated_time', models.DateTimeField(editable=False)),
                ('allowed_min', models.IntegerField(blank=True, null=True)),
                ('allowed_max', models.IntegerField(blank=True, null=True)),
                ('max_file_size', models.IntegerField(blank=True, help_text='# of kb', null=True)),
                ('folder', models.CharField(max_length=200, verbose_name='Upload To Folder')),
                ('allowed_types', models.ManyToManyField(to='uploads.FileType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_uploadtype_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_uploadtype_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='An identifier for the ending of the url - will be auto-generated based on the title for web pages.', null=True)),
                ('created_time', models.DateTimeField(editable=False)),
                ('updated_time', models.DateTimeField(editable=False)),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='External Url')),
                ('copyright_type', models.CharField(blank=True, choices=[('COPYRIGHT_FREE', 'This resource is copyright free and may be used by APA. '), ('COPYRIGHT_RESERVED', 'This resource is copyrighted.')], max_length=50, null=True, verbose_name='Copyright')),
                ('copyright_first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('copyright_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('copyright_email', models.CharField(blank=True, max_length=100, null=True)),
                ('copyright_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('creator_full_name', models.CharField(blank=True, max_length=80, null=True)),
                ('creator_company', models.CharField(blank=True, max_length=80, null=True)),
                ('resource_class', models.CharField(blank=True, help_text='Materials may be newspaper article, presentation, promotional item, plan or plan element, or other (please describe)', max_length=100, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=uploads.models.Upload.generate_file_path)),
                ('image_file', models.ImageField(blank=True, height_field='height', null=True, upload_to=uploads.models.Upload.generate_file_path, width_field='width')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='content.Content')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_upload_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_upload_updated_by', to=settings.AUTH_USER_MODEL)),
                ('upload_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='uploads.UploadType')),
                ('publish_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], default='DRAFT', max_length=50)),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='publish time')),
                ('publish_uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=36, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads_upload_published_by', to=settings.AUTH_USER_MODEL)),
                ('published_time', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('uploads.upload',),
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('uploads.upload',),
        ),
        # migrations.AddField(
        #     model_name='upload',
        #     name='publish_status',
        #     field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUBMISSION', 'Submission'), ('EARLY_RESUBMISSION', 'Early Resubmission')], default='DRAFT', max_length=50),
        # ),
        # migrations.AddField(
        #     model_name='upload',
        #     name='publish_time',
        #     field=models.DateTimeField(blank=True, null=True, verbose_name='publish time'),
        # ),
        # migrations.AddField(
        #     model_name='upload',
        #     name='publish_uuid',
        #     field=models.CharField(blank=True, default=uuid.uuid4, max_length=36, null=True),
        # ),
        # migrations.AddField(
        #     model_name='upload',
        #     name='published_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads_upload_published_by', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='upload',
        #     name='published_time',
        #     field=models.DateTimeField(blank=True, editable=False, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='upload',
        #     name='status',
        #     field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status'),
        # ),
        # migrations.AlterField(
        #     model_name='uploadtype',
        #     name='status',
        #     field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status'),
        # ),
    ]
