# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('free_students', '0001_initial'), ('free_students', '0002_auto_20160618_1220'), ('free_students', '0003_auto_20160618_1245'), ('free_students', '0004_auto_20160620_1537'), ('free_students', '0005_auto_20160620_1540'), ('free_students', '0006_auto_20160620_1544'), ('free_students', '0007_auto_20160620_1619'), ('free_students', '0008_auto_20160622_1558'), ('free_students', '0009_student_uploaded_on'), ('free_students', '0010_auto_20160623_1629'), ('free_students', '0011_auto_20160623_2003'), ('free_students', '0012_auto_20160624_1721'), ('free_students', '0013_auto_20160624_1812'), ('free_students', '0014_student_student_status'), ('free_students', '0015_auto_20160628_2304'), ('free_students', '0016_auto_20160629_2224'), ('free_students', '0017_student_duplicate_contact'), ('free_students', '0018_auto_20161018_1735')]

    initial = True

    dependencies = [
        # ('myapa', '0001_squashed_0007_auto_20161018_1735'),
('myapa', '0001_squashed_0052_auto_20160331_1650'),
        # ('myapa', '0005_auto_20160627_0240'),
        # ('myapa', '0004_contact_company_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('H', 'Hidden'), ('S', 'Staff-Use Only'), ('X', 'Marked for Deletion'), ('N', 'Not Complete'), ('C', 'Complete'), ('CA', 'Cancelled')], default='A', max_length=5, verbose_name='visibility status')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='An identifier for the ending of the url - will be auto-generated based on the title for web pages.', null=True)),
                ('created_time', models.DateTimeField(editable=False)),
                ('updated_time', models.DateTimeField(editable=False)),
                ('user_address_num', models.IntegerField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, max_length=40, null=True)),
                ('address2', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('expected_graduation_date', models.DateField(blank=True, null=True)),
                ('degree_type', models.CharField(choices=[('G', 'Graduate'), ('U', 'Undergraduate')], default='U', max_length=50)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_address1', models.CharField(blank=True, max_length=40, null=True)),
                ('secondary_address2', models.CharField(blank=True, max_length=40, null=True)),
                ('secondary_city', models.CharField(blank=True, max_length=40, null=True)),
                ('secondary_state', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('secondary_country', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_email', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_period', models.CharField(blank=True, choices=[('SPRING', 'Spring'), ('FALL', 'Fall')], max_length=10, null=True)),
                ('registration_year', models.IntegerField(blank=True, choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='myapa.Contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_students_student_created_by', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapa.School')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_students_student_updated_by', to=settings.AUTH_USER_MODEL)),
                ('uploaded_on', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('upload_status', models.CharField(blank=True, choices=[('A', 'Upload Complete'), ('P', 'Pending'), ('DP', 'Duplicate Pending'), ('DC', 'Duplicate Confirmed')], default='P', max_length=5, null=True)),
                ('duplicate_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_student', to='myapa.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_type', models.CharField(blank=True, choices=[('A001', 'Accredited Undergraduate Program'), ('A002', 'Accredited Graduate Program'), ('N001', 'Non-Accredited Undergraduate Program'), ('N002', 'Non-Planning Graduate FSTU Program'), ('N003', 'Non-Accredited Graduate Planning Program')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Accreditation type', 'verbose_name_plural': 'Accreditation types'
            },
        ),
        migrations.CreateModel(
            name='AccreditedSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation', models.ManyToManyField(blank=True, related_name='accredited_school', to='free_students.Accreditation')),
                ('school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accredited_school', to='myapa.School')),
            ],
        ),
        # migrations.AlterModelOptions(
        #     name='accreditation',
        #     options={'verbose_name': 'Accreditation type', 'verbose_name_plural': 'Accreditation types'},
        # ),
    ]
