# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_students', '0001_squashed_0018_auto_20161018_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_year',
            field=models.IntegerField(blank=True, choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], null=True),
        ),
    ]
