# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-25 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_students', '0007_auto_20200124_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditedschool',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accredited_school', to='myapa.School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='myapa.Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_students_student_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='duplicate_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_student', to='myapa.Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='myapa.School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_students_student_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
